declare const Deno:any;
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,x-client-info,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS'};
const env=(n:string)=>String(Deno.env.get(n)||'').trim();
const clean=(v:any,n=700)=>String(v??'').trim().replace(/[\u0000-\u001f]/g,' ').replace(/\s+/g,' ').slice(0,n);
const CANONICAL_VOICE='coral',CANONICAL_SPEED=1,CANONICAL_MODEL='gpt-4o-mini-tts';
const CANONICAL_INSTRUCTIONS='Speak as the Assurance Regent corporate assistant voice: warm, calm, highly natural and professional. Use steady human pacing, subtle sentence pauses, clear articulation, and never sound rushed or robotic. Keep the same audible identity used by Zari and Jivan.';
function serviceKey(){const v=env('SUPABASE_SERVICE_ROLE_KEY');if(!v)throw new Error('SUPABASE_SERVICE_ROLE_KEY is required.');return v;}
function baseUrl(){return env('SUPABASE_URL').replace(/\/$/,'');}
function clientIp(req:Request){return String(req.headers.get('cf-connecting-ip')||req.headers.get('x-forwarded-for')||req.headers.get('x-real-ip')||'unknown').split(',')[0].trim();}
function bytesToHex(bytes:Uint8Array){return [...bytes].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function sha256Text(text:string){return bytesToHex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))));}
async function ipHash(req:Request){return sha256Text(`${clientIp(req)}|${serviceKey().slice(-16)}`);}
async function serviceFetch(path:string,init:any={}){const key=serviceKey();const r=await fetch(`${baseUrl()}${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,...(init.headers||{})}});const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error||String(d||`Supabase request failed (${r.status}).`));return d;}
async function recentTts(ip_hash:string){const since=new Date(Date.now()-10*60*1000).toISOString();try{const q=new URLSearchParams({select:'id',event_type:'eq.TTS_PUBLIC',ip_hash:`eq.${ip_hash}`,created_at:`gte.${since}`,limit:'80'});const rows=await serviceFetch(`/rest/v1/assurance_regent_voice_access_audit?${q}`);return Array.isArray(rows)?rows.length:0;}catch{return 0;}}
async function audit(ip_hash:string,success:boolean,detail:any={}){try{await serviceFetch('/rest/v1/assurance_regent_voice_access_audit',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({event_type:'TTS_PUBLIC',user_id:'',success,score:null,ip_hash,detail})});}catch{}}
function arrayBufferToBase64(buf:ArrayBuffer){const bytes=new Uint8Array(buf);let out='';const step=0x8000;for(let i=0;i<bytes.length;i+=step)out+=String.fromCharCode(...bytes.subarray(i,Math.min(i+step,bytes.length)));return btoa(out);}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return new Response(JSON.stringify({error:'POST required'}),{status:405,headers:{...CORS,'content-type':'application/json'}});const ip_hash=await ipHash(req);try{if(await recentTts(ip_hash)>=60)return new Response(JSON.stringify({error:'Zari voice is temporarily rate-limited. Try again shortly.'}),{status:429,headers:{...CORS,'content-type':'application/json','cache-control':'no-store'}});const body:any=await req.json().catch(()=>({})),input=clean(body.text,700);if(!input)throw new Error('Speech text is empty.');const key=env('OPENAI_API_KEY');if(!key)throw new Error('OPENAI_API_KEY is not configured for Zari voice.');const r=await fetch('https://api.openai.com/v1/audio/speech',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:CANONICAL_MODEL,voice:CANONICAL_VOICE,input,instructions:CANONICAL_INSTRUCTIONS,speed:CANONICAL_SPEED,response_format:'mp3'})});if(!r.ok){const t=await r.text();throw new Error(t||`AI speech failed (${r.status}).`);}const bytes=await r.arrayBuffer();await audit(ip_hash,true,{voice:CANONICAL_VOICE,speed:CANONICAL_SPEED,length:input.length});return new Response(JSON.stringify({ok:true,audio_base64:arrayBufferToBase64(bytes),mime_type:'audio/mpeg',voice:CANONICAL_VOICE,speed:CANONICAL_SPEED,global:true}),{status:200,headers:{...CORS,'content-type':'application/json','cache-control':'no-store'}});}catch(e:any){await audit(ip_hash,false,{error:String(e?.message||e).slice(0,240)});return new Response(JSON.stringify({error:String(e?.message||e)}),{status:400,headers:{...CORS,'content-type':'application/json','cache-control':'no-store'}});}});