(() => {
  'use strict';
  try{window.opener=null;}catch{}
  const SUPABASE_URL='https://fubqwljypdiojpbdunjc.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY='sb_publishable_bCscsMezuyabUbEA3gaXfw_awPFhqRq';
  const endpoint=`${SUPABASE_URL}/functions/v1/recruitment-public`;
  const $=id=>document.getElementById(id);
  const params=new URLSearchParams(location.search),company=params.get('company')||'',requestedVacancy=params.get('vacancy')||'';
  let vacancies=[],activeVacancy=null;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  async function call(action,payload={}){const r=await fetch(endpoint,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({action,...payload})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'The recruitment service is unavailable.');return b;}
  function publicDate(v){if(!v)return '';const d=new Date(`${String(v).slice(0,10)}T12:00:00`);return Number.isNaN(d.getTime())?'':d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'});}
  function initials(v=''){return String(v||'AR').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'AR';}
  function logoHtml(v){return v.companyLogo?`<img src="${esc(v.companyLogo)}" alt="${esc(v.companyName||'Company')} logo" />`:esc(initials(v.companyName));}
  function vacancyUrl(id){const u=new URL(location.href);u.searchParams.set('vacancy',id);if(company)u.searchParams.set('company',company);u.hash='';return u.href;}
  function vacancyShare(v){const url=vacancyUrl(v.id),parts=[`We are hiring: ${v.title}`,v.companyName?`Company: ${v.companyName}`:'',v.location?`Location: ${v.location}`:'',v.employmentType?`Type: ${v.employmentType}`:'',v.experienceYears?`Experience: ${v.experienceYears}+ years`:'',v.closeDate?`Apply by: ${publicDate(v.closeDate)}`:'','View the full vacancy and apply:'];return {url,text:parts.filter(Boolean).join('\n'),title:`${v.title} — ${v.companyName||'Careers'}`};}
  async function shareVacancy(id){const v=vacancies.find(x=>String(x.id)===String(id));if(!v)return;const p=vacancyShare(v);if(navigator.share){try{await navigator.share({title:p.title,text:p.text,url:p.url});return;}catch(err){if(err?.name==='AbortError')return;}}try{await navigator.clipboard.writeText(`${p.text}\n${p.url}`);$('portalStatus').classList.remove('error');$('portalStatus').textContent='Job link and sharing text copied. You can paste it into WhatsApp, Facebook, LinkedIn, X or another platform.';}catch{$('portalStatus').textContent='Open this job and copy the address from your browser to share it.';}}
  function render(){const grid=$('vacancyGrid');if(!vacancies.length){grid.innerHTML='<div class="empty-public"><b>No external vacancies are open right now.</b><span>Please check again when new opportunities are published.</span></div>';return;}grid.innerHTML=vacancies.map(v=>`<article class="vacancy-card"><div class="vacancy-brand-line"><span class="vacancy-logo">${logoHtml(v)}</span><div><b>${esc(v.companyName||'Organization')}</b><small>${esc(v.department||'Opportunity')}</small></div></div><h2>${esc(v.title)}</h2><span class="job-ref">${v.jobReference?`Reference ${esc(v.jobReference)}`:'External vacancy'}</span><div class="vacancy-meta"><span>${esc(v.location||'Location not specified')}</span><span>${esc(v.employmentType||'Employment')}</span>${v.experienceYears?`<span>${esc(v.experienceYears)}+ yrs experience</span>`:''}${v.positionsCount?`<span>${esc(v.positionsCount)} position${Number(v.positionsCount)===1?'':'s'}</span>`:''}</div><p class="summary">${esc(v.description||'Applications are currently being accepted for this position.')}</p><div class="card-foot"><span class="close-date">${v.closeDate?`Closes ${esc(publicDate(v.closeDate))}`:'Open until filled'}</span><div class="card-actions"><button class="secondary share-public-job" type="button" data-share="${esc(v.id)}">↗ Share</button><button class="secondary" type="button" data-view="${esc(v.id)}">View details</button><button class="primary" type="button" data-apply="${esc(v.id)}">Apply</button></div></div></article>`).join('');grid.querySelectorAll('[data-share]').forEach(b=>b.addEventListener('click',()=>shareVacancy(b.dataset.share)));grid.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>openDetails(b.dataset.view)));grid.querySelectorAll('[data-apply]').forEach(b=>b.addEventListener('click',()=>openApplication(b.dataset.apply)));}
  function valueOr(v,fallback='Not specified'){return esc(String(v||'').trim()||fallback);}
  function openDetails(id){const v=vacancies.find(x=>String(x.id)===String(id));if(!v)return;activeVacancy=v;try{history.replaceState(null,'',vacancyUrl(v.id));document.title=`${v.title} — ${v.companyName||'Careers'}`;}catch{}$('detailCompanyName').textContent=v.companyName||'Organization';$('detailVacancyTitle').textContent=v.title||'Vacancy';$('detailVacancyMeta').innerHTML=[v.jobReference?`Ref ${v.jobReference}`:'',v.department,v.location,v.employmentType,v.salaryRange,v.reportingLine?`Reports to ${v.reportingLine}`:'',v.closeDate?`Deadline ${publicDate(v.closeDate)}`:''].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('');const img=$('detailCompanyLogo'),mark=$('detailCompanyMark');if(v.companyLogo){img.src=v.companyLogo;img.hidden=false;mark.hidden=true;}else{img.hidden=true;mark.hidden=false;mark.textContent=initials(v.companyName);}$('detailDescription').textContent=v.description||'Applications are currently being accepted for this position.';$('detailResponsibilities').textContent=v.responsibilities||'Responsibilities will be discussed during the recruitment process.';$('detailRequirements').textContent=v.requirements||'See the job description for applicant requirements.';$('detailSkills').textContent=v.skills||'Relevant professional skills for the role.';$('detailExperience').textContent=v.experienceYears?`${v.experienceYears}+ years of relevant experience.`:'Experience requirements are described above.';$('detailEducation').textContent=v.education||'Relevant education or professional qualification.';$('detailBenefits').textContent=v.benefits||v.salaryRange||'Package details will be communicated during the recruitment process.';$('detailAbout').textContent=v.aboutCompany||`${v.companyName||'The organization'} welcomes applications from qualified candidates.`;$('vacancyDetailShell').hidden=false;$('successCard').hidden=true;$('vacancyDetailShell').scrollIntoView({behavior:'smooth',block:'start'});}
  function openApplication(id){const v=vacancies.find(x=>String(x.id)===String(id));if(!v)return;activeVacancy=v;$('applicationForm').reset();$('applicationCompanyId').value=v.companyId;$('applicationVacancyId').value=v.id;$('applicationTitle').textContent=`Apply for ${v.title}`;$('applicationShell').hidden=false;$('successCard').hidden=true;$('applicationState').textContent='';$('applicationShell').scrollIntoView({behavior:'smooth',block:'start'});}
  function fileBase64(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');const r=new FileReader();r.onload=()=>resolve(String(r.result||'').split(',')[1]||'');r.onerror=()=>reject(new Error(`Could not read ${file.name||'the selected file'}.`));r.readAsDataURL(file);});}
  async function attachmentPayload(files){const rows=[...(files||[])];if(rows.length>4)throw new Error('Choose no more than 4 additional attachments.');const blocked=/\.(exe|com|bat|cmd|msi|scr|ps1|vbs|js|mjs|cjs|html?|svg|php|py|rb|pl|sh|jar|apk|dmg|iso)$/i;let total=0;const out=[];for(const f of rows){if(blocked.test(f.name||''))throw new Error(`${f.name} is not an accepted recruitment attachment.`);if(f.size>5*1024*1024)throw new Error(`${f.name} is larger than 5 MB.`);total+=f.size;if(total>8*1024*1024)throw new Error('Additional attachments must be 8 MB or smaller in total.');out.push({name:f.name,type:f.type||'application/octet-stream',size:f.size,base64:await fileBase64(f)});}return out;}
  async function submit(e){e.preventDefault();const btn=$('submitApplication'),state=$('applicationState'),file=$('applicationResume').files?.[0];try{btn.disabled=true;state.classList.remove('error');state.textContent='Submitting securely…';if(file&&file.size>6*1024*1024)throw new Error('CV must be 6 MB or smaller.');const [resume,attachments]=await Promise.all([fileBase64(file),attachmentPayload($('applicationAttachments').files)]);const b=await call('apply',{company_id:$('applicationCompanyId').value,vacancy_id:$('applicationVacancyId').value,name:$('applicationName').value,email:$('applicationEmail').value,phone:$('applicationPhone').value,location:$('applicationLocation').value,experience_years:$('applicationExperienceYears').value,qualification:$('applicationQualification').value,skills_summary:$('applicationSkills').value,cover_note:$('applicationCover').value,resume_base64:resume,resume_name:file?.name||'',resume_type:file?.type||'',attachments,consent:$('applicationConsent').checked,website:$('applicationWebsite').value});$('applicationShell').hidden=true;$('vacancyDetailShell').hidden=true;$('successCard').hidden=false;$('successMessage').textContent=`Thank you. Your application for ${b.vacancy_title||'this vacancy'} has been received by Human Resources.`;$('successCard').scrollIntoView({behavior:'smooth',block:'center'});}catch(err){state.classList.add('error');state.textContent=err.message||'Application could not be submitted.';}finally{btn.disabled=false;}}
  async function boot(){try{$('applicationForm').addEventListener('submit',submit);$('closeApplication').addEventListener('click',()=>{$('applicationShell').hidden=true;});$('closeVacancyDetail').addEventListener('click',()=>{$('vacancyDetailShell').hidden=true;});$('detailApplyButton').addEventListener('click',()=>activeVacancy&&openApplication(activeVacancy.id));$('detailShareButton').addEventListener('click',()=>activeVacancy&&shareVacancy(activeVacancy.id));const b=await call('list_vacancies',{company_id:company,vacancy_id:requestedVacancy});vacancies=Array.isArray(b.vacancies)?b.vacancies:[];if(vacancies[0]?.companyName)$('careersTitle').textContent=`${vacancies[0].companyName} Careers`;$('portalStatus').textContent=vacancies.length?`${vacancies.length} published opportunit${vacancies.length===1?'y':'ies'} available.`:'No published opportunities are currently available.';render();if(requestedVacancy&&vacancies.some(v=>String(v.id)===String(requestedVacancy)))openDetails(requestedVacancy);}catch(err){$('portalStatus').classList.add('error');$('portalStatus').textContent=err.message||'The recruitment page is temporarily unavailable.';$('vacancyGrid').innerHTML='';}}
  boot();
})();
