(() => {
  'use strict';
  try{window.opener=null;}catch{}
  const SUPABASE_URL='https://fubqwljypdiojpbdunjc.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY='sb_publishable_bCscsMezuyabUbEA3gaXfw_awPFhqRq';
  const endpoint=`${SUPABASE_URL}/functions/v1/recruitment-public`,$=id=>document.getElementById(id),token=new URLSearchParams(location.search).get('token')||'';
  async function call(){const r=await fetch(endpoint,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({action:'interview_details',token})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Interview invitation could not be verified.');return b.interview;}
  function fmt(v,zone){const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v||'');try{return new Intl.DateTimeFormat(undefined,{dateStyle:'full',timeStyle:'short',timeZone:zone||'Africa/Lusaka'}).format(d);}catch{return d.toLocaleString();}}
  async function boot(){try{if(!token)throw new Error('This interview invitation is incomplete.');const i=await call();$('interviewTitle').textContent=i.vacancy_title||'Recruitment interview';$('interviewIntro').textContent=`Welcome ${i.candidate_name||'candidate'}. Your interview room is ready for the scheduled session.`;$('interviewDetails').hidden=false;$('interviewDetails').innerHTML=`<article><small>Candidate</small><b>${String(i.candidate_name||'')}</b></article><article><small>Position</small><b>${String(i.vacancy_title||'')}</b></article><article><small>Scheduled time</small><b>${fmt(i.scheduled_at,i.time_zone)}</b></article><article><small>Time zone</small><b>${String(i.time_zone||'Africa/Lusaka')}</b></article>`;const validMeet=(()=>{try{const u=new URL(String(i.meet_url||''));return u.protocol==='https:'&&u.hostname.toLowerCase()==='meet.google.com'&&u.pathname.length>1?u.href:'';}catch{return '';}})(),active=String(i.status||'SCHEDULED')==='SCHEDULED'&&Boolean(validMeet);$('roomEntry').hidden=!active;if(active){$('joinRoom').href=validMeet;$('joinRoom').addEventListener('click',()=>{try{window.opener=null;}catch{}});}else if(String(i.status||'SCHEDULED')!=='SCHEDULED'){$('interviewIntro').textContent=`This interview is marked ${String(i.status||'').toLowerCase()}. The room is not available from this invitation.`;}else{$('interviewIntro').textContent='The company interview room has not yet been configured. Please contact Human Resources for an updated invitation.';}}catch(err){$('interviewTitle').textContent='Interview invitation unavailable';$('interviewIntro').textContent=err.message||'This interview invitation is not active.';}}
  boot();
})();
