declare const Deno:any;
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,x-client-info,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS'};
const env=(n:string)=>String(Deno.env.get(n)||'').trim();
const clean=(v:any,n=4000)=>String(v??'').trim().replace(/[\u0000-\u001f]/g,' ').slice(0,n);
const q=(v:any)=>encodeURIComponent(String(v??''));
function pubKey(){const raw=env('SUPABASE_PUBLISHABLE_KEYS');if(raw){try{const x=JSON.parse(raw);return String(x.default||Object.values(x)[0]||'');}catch{}}return env('SUPABASE_PUBLISHABLE_KEY')||env('SUPABASE_ANON_KEY');}
async function rpc(name:string,payload:any){const base=env('SUPABASE_URL').replace(/\/$/,'');const key=pubKey();const r=await fetch(`${base}/rest/v1/rpc/${q(name)}`,{method:'POST',headers:{apikey:key,'content-type':'application/json'},body:JSON.stringify(payload||{})});const t=await r.text();let b:any=null;try{b=t?JSON.parse(t):null}catch{b=t}if(!r.ok)throw new Error(b?.message||b?.error||String(b||`RPC ${r.status}`));return b;}
const VOICES=new Set(['alloy','ash','ballad','coral','echo','fable','onyx','nova','sage','shimmer','verse','marin','cedar']);
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return new Response(JSON.stringify({error:'POST required'}),{status:405,headers:{...CORS,'content-type':'application/json'}});try{const z:any=await req.json().catch(()=>({})),token=clean(z.session_token,260);if(!token)throw new Error('Assurance Regent session is required.');const actor=await rpc('assurance_regent_browser_actor_from_token',{p_token:token});const prefs=await rpc('assurance_regent_browser_ai_preferences_get',{p_token:token});const agent=clean(z.agent,20).toUpperCase()==='ZARI'?'ZARI':'JIVAN';let voice=clean(z.voice_override,30).toLowerCase()||String(agent==='ZARI'?prefs?.zariVoice:prefs?.jivanVoice||'marin').toLowerCase();if(!VOICES.has(voice))voice=agent==='ZARI'?'coral':'marin';const speed=Math.max(.75,Math.min(1.35,Number(z.speed_override||prefs?.voiceSpeed||1)));const input=clean(z.text,4096);if(!input)throw new Error('Speech text is empty.');const key=env('OPENAI_API_KEY');if(!key)throw new Error('OPENAI_API_KEY is not configured for AI voice.');const instructions=agent==='ZARI'?'Speak like a warm, calm, highly natural professional receptionist. Use human pacing, subtle sentence pauses, and never sound rushed or robotic.':'Speak like a composed, intelligent professional colleague. Use natural phrasing, warm human pacing, subtle pauses, and do not announce markdown, hashes, bullets, or list numbering.';const r=await fetch('https://api.openai.com/v1/audio/speech',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-4o-mini-tts',voice,input,instructions,speed,response_format:'mp3'})});if(!r.ok){const t=await r.text();throw new Error(t||`AI speech failed (${r.status}).`);}const bytes=await r.arrayBuffer();return new Response(bytes,{status:200,headers:{...CORS,'content-type':'audio/mpeg','cache-control':'no-store','x-assurance-agent':agent,'x-assurance-voice':voice,'x-assurance-user':clean(actor?.id,120)}});}catch(e:any){return new Response(JSON.stringify({error:String(e?.message||e)}),{status:400,headers:{...CORS,'content-type':'application/json','cache-control':'no-store'}});}});
