declare const Deno:any;
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,x-client-info,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS'};
const env=(n:string)=>String(Deno.env.get(n)||'').trim();
const clean=(v:any,n=4000)=>String(v??'').trim().replace(/[\u0000-\u001f]/g,' ').slice(0,n);
const q=(v:any)=>encodeURIComponent(String(v??''));
const CANONICAL_VOICE='coral';
const CANONICAL_SPEED=1;
const CANONICAL_MODEL='gpt-4o-mini-tts';
const CANONICAL_INSTRUCTIONS='Speak as the Assurance Regent corporate assistant voice: warm, calm, highly natural and professional. Use steady human pacing, subtle sentence pauses, clear articulation, and never sound rushed or robotic. Keep the same audible identity whether the active assistant is Zari or Jivan.';
function pubKey(){const raw=env('SUPABASE_PUBLISHABLE_KEYS');if(raw){try{const x=JSON.parse(raw);return String(x.default||Object.values(x)[0]||'');}catch{}}return env('SUPABASE_PUBLISHABLE_KEY')||env('SUPABASE_ANON_KEY');}
async function rpc(name:string,payload:any){const base=env('SUPABASE_URL').replace(/\/$/,'');const key=pubKey();const r=await fetch(`${base}/rest/v1/rpc/${q(name)}`,{method:'POST',headers:{apikey:key,'content-type':'application/json'},body:JSON.stringify(payload||{})});const t=await r.text();let b:any=null;try{b=t?JSON.parse(t):null}catch{b=t}if(!r.ok)throw new Error(b?.message||b?.error||String(b||`RPC ${r.status}`));return b;}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return new Response(JSON.stringify({error:'POST required'}),{status:405,headers:{...CORS,'content-type':'application/json'}});try{const z:any=await req.json().catch(()=>({})),token=clean(z.session_token,260);if(!token)throw new Error('Assurance Regent session is required.');const actor=await rpc('assurance_regent_browser_actor_from_token',{p_token:token});const agent=clean(z.agent,20).toUpperCase()==='ZARI'?'ZARI':'JIVAN';const input=clean(z.text,4096);if(!input)throw new Error('Speech text is empty.');const key=env('OPENAI_API_KEY');if(!key)throw new Error('OPENAI_API_KEY is not configured for AI voice.');const r=await fetch('https://api.openai.com/v1/audio/speech',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:CANONICAL_MODEL,voice:CANONICAL_VOICE,input,instructions:CANONICAL_INSTRUCTIONS,speed:CANONICAL_SPEED,response_format:'mp3'})});if(!r.ok){const t=await r.text();throw new Error(t||`AI speech failed (${r.status}).`);}const bytes=await r.arrayBuffer();return new Response(bytes,{status:200,headers:{...CORS,'content-type':'audio/mpeg','cache-control':'no-store','x-assurance-agent':agent,'x-assurance-voice':CANONICAL_VOICE,'x-assurance-voice-speed':String(CANONICAL_SPEED),'x-assurance-voice-global':'true','x-assurance-user':clean(actor?.id,120)}});}catch(e:any){return new Response(JSON.stringify({error:String(e?.message||e)}),{status:400,headers:{...CORS,'content-type':'application/json','cache-control':'no-store'}});}});