// Assurance Regent v6.3.11 Zari Reception & Authentication Operator — voice instructions, enrollment, dynamic challenge, speaker verification and passwordless session issuance.
// Private voice-template enrollment, dynamic phrase verification and browser-session issuance.
declare const Deno:any;
// Uses only Supabase service-role access plus the existing OPENAI_API_KEY for challenge transcription.

const corsHeaders={
  'Access-Control-Allow-Origin':'*',
  'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods':'POST, OPTIONS'
};
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,'Content-Type':'application/json; charset=utf-8'}});}
function env(name){return String(Deno.env.get(name)||'').trim();}
function baseUrl(){const v=env('SUPABASE_URL');if(!v)throw new Error('SUPABASE_URL is not configured.');return v.replace(/\/$/,'');}
function serviceKey(){const v=env('SUPABASE_SERVICE_ROLE_KEY');if(!v)throw new Error('SUPABASE_SERVICE_ROLE_KEY is required for Zari voice access.');return v;}
function serviceHeaders(extra:any={}){const key=serviceKey();return {apikey:key,Authorization:`Bearer ${key}`,...extra};}
async function serviceFetch(path:string,init:any={}){const r=await fetch(`${baseUrl()}${path}`,{...init,headers:{...serviceHeaders(),...(init.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null;}catch{data=text;}if(!r.ok)throw new Error(data?.message||data?.error||data?.hint||String(data||`Supabase service request failed (${r.status}).`));return data;}
async function serviceRpc(name:string,payload:any){return serviceFetch(`/rest/v1/rpc/${encodeURIComponent(name)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload||{})});}
async function selectRows(table:string,params:any={}){const q=new URLSearchParams(params);return serviceFetch(`/rest/v1/${table}?${q.toString()}`,{headers:{Accept:'application/json'}});}
async function insertRows(table:string,rows:any,representation=false){return serviceFetch(`/rest/v1/${table}`,{method:'POST',headers:{'Content-Type':'application/json',Prefer:representation?'return=representation':'return=minimal'},body:JSON.stringify(rows)});}
async function patchRows(table:string,filter:any,values:any){const q=new URLSearchParams(filter);return serviceFetch(`/rest/v1/${table}?${q.toString()}`,{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(values)});}

function bytesToHex(bytes){return [...bytes].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function sha256Text(text){return bytesToHex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(text||'')))));}
function clientIp(req){return String(req.headers.get('cf-connecting-ip')||req.headers.get('x-forwarded-for')||req.headers.get('x-real-ip')||'unknown').split(',')[0].trim();}
async function ipHash(req){return sha256Text(`${clientIp(req)}|${serviceKey().slice(-16)}`);}
function randomToken(bytes=32){const b=new Uint8Array(bytes);crypto.getRandomValues(b);return bytesToHex(b);}
function decodeBase64(s){const raw=atob(String(s||''));const out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function average(arr){return arr.length?arr.reduce((a,b)=>a+b,0)/arr.length:0;}
function std(arr,mean=average(arr)){return arr.length?Math.sqrt(arr.reduce((s,v)=>s+(v-mean)*(v-mean),0)/arr.length):0;}

function parseWav(bytes:Uint8Array,options:any={}){
  if(bytes.length<44||String.fromCharCode(...bytes.slice(0,4))!=='RIFF'||String.fromCharCode(...bytes.slice(8,12))!=='WAVE')throw new Error('Voice recording must be PCM WAV audio.');
  const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let pos=12,fmt=null,dataStart=-1,dataSize=0;
  while(pos+8<=bytes.length){const id=String.fromCharCode(...bytes.slice(pos,pos+4));const size=dv.getUint32(pos+4,true);const start=pos+8;if(id==='fmt '){fmt={audioFormat:dv.getUint16(start,true),channels:dv.getUint16(start+2,true),sampleRate:dv.getUint32(start+4,true),bits:dv.getUint16(start+14,true)};}else if(id==='data'){dataStart=start;dataSize=Math.min(size,bytes.length-start);break;}pos=start+size+(size%2);}
  if(!fmt||dataStart<0||fmt.audioFormat!==1||fmt.bits!==16||fmt.channels<1||fmt.channels>2)throw new Error('Voice recording must be 16-bit PCM WAV audio.');
  const frames=Math.floor(dataSize/(2*fmt.channels)),minSeconds=Math.max(.35,Number(options?.minSeconds??1.15)),maxSeconds=Math.max(minSeconds+1,Number(options?.maxSeconds??15));if(frames<fmt.sampleRate*minSeconds)throw new Error(`Voice sample is too short. Speak for at least ${Math.ceil(minSeconds)} second${Math.ceil(minSeconds)===1?'':'s'}.`);if(frames>fmt.sampleRate*maxSeconds)throw new Error(`Voice sample is too long. Keep this recording under ${Math.floor(maxSeconds)} seconds.`);
  const out=new Float32Array(frames);let off=dataStart;for(let i=0;i<frames;i++){let sum=0;for(let c=0;c<fmt.channels;c++){sum+=dv.getInt16(off,true)/32768;off+=2;}out[i]=sum/fmt.channels;}return {samples:out,sampleRate:fmt.sampleRate};
}
function resampleLinear(input,fromRate,toRate=16000){if(fromRate===toRate)return input;const n=Math.max(1,Math.floor(input.length*toRate/fromRate)),out=new Float32Array(n),ratio=fromRate/toRate;for(let i=0;i<n;i++){const p=i*ratio,j=Math.floor(p),f=p-j,a=input[Math.min(j,input.length-1)]||0,b=input[Math.min(j+1,input.length-1)]||a;out[i]=a+(b-a)*f;}return out;}
function normalizePcm(samples){let mean=0;for(const v of samples)mean+=v;mean/=samples.length||1;let peak=0;const out=new Float32Array(samples.length);for(let i=0;i<samples.length;i++){out[i]=samples[i]-mean;peak=Math.max(peak,Math.abs(out[i]));}if(peak<0.01)throw new Error('Voice sample is too quiet.');const gain=Math.min(8,0.92/peak);for(let i=0;i<out.length;i++)out[i]*=gain;return out;}
function fftPower(frame,n=512){const re=new Float64Array(n),im=new Float64Array(n);for(let i=0;i<frame.length&&i<n;i++)re[i]=frame[i];for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){let t=re[i];re[i]=re[j];re[j]=t;t=im[i];im[i]=im[j];im[j]=t;}}for(let len=2;len<=n;len<<=1){const ang=-2*Math.PI/len,wlr=Math.cos(ang),wli=Math.sin(ang);for(let i=0;i<n;i+=len){let wr=1,wi=0;for(let j=0;j<len/2;j++){const uR=re[i+j],uI=im[i+j],vR=re[i+j+len/2]*wr-im[i+j+len/2]*wi,vI=re[i+j+len/2]*wi+im[i+j+len/2]*wr;re[i+j]=uR+vR;im[i+j]=uI+vI;re[i+j+len/2]=uR-vR;im[i+j+len/2]=uI-vI;const nw=wr*wlr-wi*wli;wi=wr*wli+wi*wlr;wr=nw;}}}const p=new Float64Array(n/2+1);for(let i=0;i<p.length;i++)p[i]=(re[i]*re[i]+im[i]*im[i])/n;return p;}
function hzToMel(hz){return 2595*Math.log10(1+hz/700);}function melToHz(m){return 700*(10**(m/2595)-1);}
function melBank(sampleRate,nfft=512,count=26,minHz=80,maxHz=7600){const min=hzToMel(minHz),max=hzToMel(Math.min(maxHz,sampleRate/2-100)),points=[];for(let i=0;i<count+2;i++)points.push(melToHz(min+(max-min)*i/(count+1)));const bins=points.map(h=>Math.floor((nfft+1)*h/sampleRate));return Array.from({length:count},(_,m)=>{const a=Math.max(0,bins[m]),b=Math.max(a+1,bins[m+1]),c=Math.max(b+1,bins[m+2]);return {a,b,c};});}
function mfccForPower(power,bank,count=12){const logs=bank.map(({a,b,c})=>{let e=0;for(let k=a;k<b&&k<power.length;k++)e+=power[k]*(k-a)/(b-a);for(let k=b;k<c&&k<power.length;k++)e+=power[k]*(c-k)/(c-b);return Math.log(Math.max(e,1e-10));});const out=[];for(let m=1;m<=count;m++){let s=0;for(let i=0;i<logs.length;i++)s+=logs[i]*Math.cos(Math.PI*m*(i+.5)/logs.length);out.push(s);}return out;}
function pitchForFrame(frame,sr=16000){let energy=0;for(const v of frame)energy+=v*v;if(energy/frame.length<0.001)return 0;let bestLag=0,best=-1;const minLag=Math.floor(sr/360),maxLag=Math.floor(sr/70);for(let lag=minLag;lag<=maxLag;lag+=2){let num=0,a=0,b=0;for(let i=0;i<frame.length-lag;i+=2){const x=frame[i],y=frame[i+lag];num+=x*y;a+=x*x;b+=y*y;}const corr=num/Math.sqrt(Math.max(a*b,1e-9));if(corr>best){best=corr;bestLag=lag;}}return best>.32&&bestLag?sr/bestLag:0;}
function voiceFeatureFromWav(bytes){const parsed=parseWav(bytes),pcm=normalizePcm(resampleLinear(parsed.samples,parsed.sampleRate,16000)),sr=16000,frameLen=400,hop=160,frames=[];let maxRms=0;for(let s=0;s+frameLen<=pcm.length;s+=hop){const f=pcm.slice(s,s+frameLen);let e=0,z=0;for(let i=0;i<f.length;i++){e+=f[i]*f[i];if(i&&((f[i]>=0)!=(f[i-1]>=0)))z++;}const rms=Math.sqrt(e/f.length);maxRms=Math.max(maxRms,rms);frames.push({f,rms,zcr:z/f.length});}const voiced=frames.filter(x=>x.rms>=Math.max(.025,maxRms*.16));if(voiced.length<12)throw new Error('Zari could not isolate enough clear speech. Reduce background noise and try again.');const limit=180,step=Math.max(1,Math.floor(voiced.length/limit)),selected=voiced.filter((_,i)=>i%step===0).slice(0,limit),bank=melBank(sr),coeffs=Array.from({length:12},()=>[]),zcrs=[],pitches=[];for(let idx=0;idx<selected.length;idx++){const src=selected[idx].f,win=new Float64Array(frameLen);for(let i=0;i<frameLen;i++)win[i]=src[i]*(.54-.46*Math.cos(2*Math.PI*i/(frameLen-1)));const m=mfccForPower(fftPower(win),bank,12);m.forEach((v,i)=>coeffs[i].push(v));zcrs.push(selected[idx].zcr);if(idx%4===0){const p=pitchForFrame(src,sr);if(p>0)pitches.push(p);}}const feature=[];for(const c of coeffs)feature.push(average(c));for(const c of coeffs)feature.push(std(c));const pm=average(pitches),ps=std(pitches);feature.push(pm?pm/250:0,ps/120,average(zcrs)*8,Math.log1p(pcm.length/sr));const norm=Math.sqrt(feature.reduce((s,v)=>s+v*v,0))||1;return {vector:feature.map(v=>v/norm),duration:pcm.length/sr,pitch_hz:pm||0,voiced_frames:voiced.length};}
function cosine(a,b){const n=Math.min(a?.length||0,b?.length||0);if(!n)return -1;let dot=0,aa=0,bb=0;for(let i=0;i<n;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i];}return dot/Math.sqrt(Math.max(aa*bb,1e-12));}
function centroid(vectors){if(!vectors.length)return [];const n=vectors[0].length,out=new Array(n).fill(0);for(const v of vectors)for(let i=0;i<n;i++)out[i]+=Number(v[i]||0);for(let i=0;i<n;i++)out[i]/=vectors.length;const norm=Math.sqrt(out.reduce((s,v)=>s+v*v,0))||1;return out.map(v=>v/norm);}
function enrollmentTemplate(vectors){const c=centroid(vectors),pairs=[];for(let i=0;i<vectors.length;i++)for(let j=i+1;j<vectors.length;j++)pairs.push(cosine(vectors[i],vectors[j]));const selfFloor=pairs.length?Math.min(...pairs):cosine(vectors[0],c),threshold=clamp(selfFloor-.055,.78,.94);return {version:1,centroid:c,threshold:Number(threshold.toFixed(4)),self_similarity:Number(average(pairs.length?pairs:[selfFloor]).toFixed(4)),dimensions:c.length};}

const CHALLENGE_WORDS=['cedar','river','orbit','silver','cobalt','harbor','meadow','summit','amber','matrix','falcon','vertex'];
function randomInt(max){const b=new Uint32Array(1);crypto.getRandomValues(b);return b[0]%max;}
function challengePhrase(){return `Jivan access ${CHALLENGE_WORDS[randomInt(CHALLENGE_WORDS.length)]} ${randomInt(10)} ${randomInt(10)}`;}
function normalizeTranscript(text){const nums={zero:'0',oh:'0',one:'1',two:'2',to:'2',too:'2',three:'3',four:'4',for:'4',five:'5',six:'6',seven:'7',eight:'8',ate:'8',nine:'9'};return String(text||'').toLowerCase().replace(/jee?v[ae]n|given|givan/g,'jivan').replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(Boolean).map(w=>nums[w]??w).join(' ').replace(/\s+/g,' ').trim();}
function transcriptMatches(transcript,phrase){const a=normalizeTranscript(transcript),b=normalizeTranscript(phrase);if(a===b)return true;const bt=b.split(' ');return bt.every(t=>a.split(' ').includes(t));}
async function transcribeWav(bytes){const key=env('OPENAI_API_KEY');if(!key)throw new Error('OPENAI_API_KEY is required for secure dynamic-phrase voice recognition.');const model=env('OPENAI_TRANSCRIBE_MODEL')||'gpt-4o-mini-transcribe',form=new FormData();form.append('file',new Blob([bytes],{type:'audio/wav'}),'voice-access.wav');form.append('model',model);const r=await fetch('https://api.openai.com/v1/audio/transcriptions',{method:'POST',headers:{Authorization:`Bearer ${key}`},body:form});const text=await r.text();let data:any={};try{data=text?JSON.parse(text):{};}catch{data={};}if(!r.ok)throw new Error(data?.error?.message||`Voice transcription failed (${r.status}).`);return String(data?.text||'').trim();}

function normalizeSpokenEntry(value=''){return String(value||'').trim().replace(/\s+(?:at)\s+/ig,'@').replace(/\s+(?:dot)\s+/ig,'.').replace(/\s+/g,'').replace(/[.,;]+$/,'');}
function cleanInstructionValue(value=''){return String(value||'').trim().replace(/^[\s:,-]+|[\s,;]+$/g,'').slice(0,140);}
function extractInstructionValue(text,labelPattern,stopPattern='and|then|please|sign|login|log in|recognize|verify|record|enroll|create|submit|register'){
  const re=new RegExp(`(?:${labelPattern})\\s*(?:is|as|:)?\\s+(.+?)(?=\\s+(?:${stopPattern})\\b|$)`,'i'),m=String(text||'').match(re);return cleanInstructionValue(m?.[1]||'');
}
function interpretAuthInstruction(text,surface='signin'){
  const raw=String(text||'').trim(),lower=raw.toLowerCase(),isSignup=String(surface||'signin').toLowerCase()==='signup',fields:any={};
  if(!raw)return {action:'NONE',fields,reply:'I could not hear a clear instruction.'};
  if(/\bpassword\b/i.test(raw))return {action:'NONE',fields,reply:'For security, Zari will not capture or repeat a spoken password. Type it privately or use voice recognition.'};
  if(isSignup){
    if(/\b(?:back to|open|go to)\s+sign ?in\b|\blog ?in\b/i.test(raw))return {action:'OPEN_SIGNIN',fields,reply:'Returning to secure sign-in.'};
    if(/\badministrator|\badmin\b/i.test(lower))fields.role='Administrator';else if(/\bemployee\b/i.test(lower))fields.role='Employee';
    const userId=extractInstructionValue(raw,'employee\\s*id|user\\s*name|username','and|then|please|company|my name|name|position|job title|email|record|enroll|create|submit|register');if(userId)fields.user_id=normalizeSpokenEntry(userId);
    const company=extractInstructionValue(raw,'company\\s*(?:code|id)','and|then|please|my name|name|position|job title|email|record|enroll|create|submit|register');if(company)fields.company_code=normalizeSpokenEntry(company);
    const name=extractInstructionValue(raw,'my\\s+name|full\\s+name|name','and|then|please|position|job title|email|record|enroll|create|submit|register');if(name)fields.name=cleanInstructionValue(name);
    const position=extractInstructionValue(raw,'position|job\\s*title','and|then|please|email|record|enroll|create|submit|register');if(position)fields.position=cleanInstructionValue(position);
    const email=extractInstructionValue(raw,'email(?:\\s+address)?','and|then|please|record|enroll|create|submit|register');if(email)fields.email=normalizeSpokenEntry(email);
    if(/\b(?:record|enroll|register)\s+(?:my\s+)?voice\b|\bvoice\s+enrollment\b/i.test(raw))return {action:'START_ENROLLMENT',fields,reply:'I have prepared the registration details I heard. Starting the next voice-enrollment sample.'};
    if(/\b(?:create|submit|register)\s+(?:my\s+)?(?:account|registration)\b|\bcreate account\b/i.test(raw))return {action:'SUBMIT_SIGNUP',fields,reply:'I have prepared the registration details. I will submit after the private password requirement is satisfied.'};
    const changed=Object.keys(fields).length>0;return {action:changed?'SET_FIELDS':'HELP',fields,reply:changed?'I updated the registration fields I could identify. You can tell me more details or record your voice samples.':'Tell me your employee ID, company code, name, position or email, or ask me to enroll your voice.'};
  }
  if(/\b(?:sign\s*(?:me\s+)?up|register(?:\s+me)?|create\s+(?:me\s+)?(?:an\s+)?account|open\s+registration)\b/i.test(raw))return {action:'OPEN_SIGNUP',fields,reply:'Opening account registration. Zari will stay available there for voice enrollment.'};
  if(/\bdeveloper\b/.test(lower))fields.role='Developer';else if(/\badministrator|\badmin\b/.test(lower))fields.role='Administrator';else if(/\bemployee\b/.test(lower))fields.role='Employee';
  const identifier=extractInstructionValue(raw,'username|user\\s*name|employee\\s*id|email(?:\\s+address)?|sign\\s*in\\s*as|login\\s*as|log\\s*in\\s*as|my\\s+account|my\\s+username|my\\s+email','and|then|please|sign|login|log in|recognize|verify|use voice');if(identifier)fields.identifier=normalizeSpokenEntry(identifier);
  if(/\b(?:recognize|verify|identify)\s+(?:my\s+)?voice\b|\bvoice\s+(?:recognition|sign ?in|login)\b/i.test(raw))return {action:'START_RECOGNITION',fields,reply:'Starting Zari voice recognition. I will give you a one-time phrase to repeat.'};
  if(/\b(sign ?in|login|log in|enter|open)\b/i.test(raw))return {action:'SIGN_IN',fields,reply:'I prepared the account details I heard. I can sign in with an already-entered private password, or verify your voice.'};
  const changed=Object.keys(fields).length>0;return {action:changed?'SET_FIELDS':'HELP',fields,reply:changed?'I updated the sign-in details I could identify. Type your password privately or ask me to recognize your voice.':'Tell me your username, email or employee ID, ask me to recognize your voice, or say sign up.'};
}

async function uploadPrivateSample(userId,bytes,index){const path=`${encodeURIComponent(userId)}/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${index+1}.wav`;const r=await fetch(`${baseUrl()}/storage/v1/object/assurance-regent-voiceprints/${path}`,{method:'POST',headers:{...serviceHeaders(),Authorization:`Bearer ${serviceKey()}`,'Content-Type':'audio/wav','x-upsert':'false'},body:bytes});if(!r.ok){const t=await r.text();throw new Error(`Could not store the private voice enrollment sample. ${t.slice(0,180)}`);}return path;}
async function audit(eventType,userId,success,score,ip_hash,detail={}){try{await insertRows('assurance_regent_voice_access_audit',{event_type:eventType,user_id:userId||'',success:Boolean(success),score:Number.isFinite(score)?score:null,ip_hash,detail});}catch(e){console.warn('Voice audit write failed',e);}}
async function recentAttempts(ip_hash){const since=new Date(Date.now()-10*60*1000).toISOString();try{const rows=await selectRows('assurance_regent_voice_access_audit',{select:'id',ip_hash:`eq.${ip_hash}`,created_at:`gte.${since}`,limit:'50'});return Array.isArray(rows)?rows.length:0;}catch{return 0;}}
async function findCredential(userId){const rows=await selectRows('assurance_regent_browser_credentials',{select:'user_id,username,email,active,approval_status',or:`(user_id.ilike.${userId},username.ilike.${userId},email.ilike.${userId})`,limit:'1'});return Array.isArray(rows)?rows[0]||null:null;}
async function applicationState(){const rows=await selectRows('assurance_regent_state',{select:'state_value',state_key:'eq.browser-client-state',limit:'1'});return rows?.[0]?.state_value||{};}
async function issueBrowserSession(userId,requestedRole=''){
  const credRows=await selectRows('assurance_regent_browser_credentials',{select:'user_id,username,email,active,approval_status',user_id:`eq.${userId}`,limit:'1'}),cred=credRows?.[0];if(!cred)throw new Error('Voice profile account no longer exists.');if(String(cred.approval_status||'APPROVED')==='PENDING')throw new Error('This account is awaiting Developer approval.');if(['REJECTED','SUSPENDED'].includes(String(cred.approval_status||''))||cred.active===false)throw new Error('This account is not active for voice sign-in.');
  const state=await applicationState();let user=null;if(userId==='Dvp')user={id:'Dvp',username:'Dvp',name:'Developer',email:'',position:'System Developer',companyId:'',role:'Developer',hiddenFromDirectory:true,active:true,approvalStatus:'APPROVED'};else{user=(state?.auth?.accounts||[]).find(x=>String(x?.id||'')===String(userId))||null;if(!user)throw new Error('This voice profile is not connected to an Assurance Regent account.');const company=(state?.auth?.companies||[]).find(c=>String(c?.id||'')===String(user.companyId||''));if(!company)throw new Error('This account is not connected to an active company directory.');if(company.systemEnabled===false)throw new Error('Company access is currently offline. Use the normal sign-in screen for billing instructions.');}
  if(requestedRole&&String(user.role||'Employee')!==String(requestedRole))throw new Error(`This voice belongs to an account registered as ${user.role||'Employee'}.`);
  const token=randomToken(32),tokenHash=await sha256Text(token);await insertRows('assurance_regent_auth_sessions',{token_hash:tokenHash,user_id:userId,expires_at:new Date(Date.now()+12*60*60*1000).toISOString(),created_at:new Date().toISOString(),updated_at:new Date().toISOString()});return {token,userId,user};
}

Deno.serve(async req=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({error:'Use POST for Zari voice access.'},405);
  const ip_hash=await ipHash(req);try{
    const attempts=await recentAttempts(ip_hash);if(attempts>=30)return json({error:'Voice access is temporarily rate-limited. Try again later.'},429);
    const body=await req.json().catch(()=>({})),mode=String(body?.mode||'').toLowerCase();
    if(mode==='status'){const health=await serviceRpc('assurance_regent_browser_voice_access_health',{});return json({ok:true,voice_access:health,transcription:Boolean(env('OPENAI_API_KEY'))});}
    if(mode==='transcribe'||mode==='auth_instruction'){
      const bytes=decodeBase64(body?.audio_base64||'');if(bytes.length>2_000_000)throw new Error('Voice instruction recording is too large.');parseWav(bytes,{minSeconds:.45,maxSeconds:58});const text=await transcribeWav(bytes);if(mode==='auth_instruction'){const surface=String(body?.surface||'signin').toLowerCase()==='signup'?'signup':'signin',intent=interpretAuthInstruction(text,surface);await audit('AUTH_INSTRUCTION','',true,null,ip_hash,{surface,action:intent.action,length:text.length,field_names:Object.keys(intent.fields||{})});return json({ok:true,operator:'ZARI',surface,transcript:text,intent,reply:intent.reply});}await audit('INSTRUCTION_TRANSCRIBE','',true,null,ip_hash,{length:text.length});return json({ok:true,text});
    }
    if(mode==='enroll'){
      const userInput=String(body?.user_id||'').trim(),password=String(body?.password||''),samples=Array.isArray(body?.samples)?body.samples.slice(0,3):[];if(!userInput||!password)throw new Error('Username and password are required for voice enrollment.');if(samples.length<3)throw new Error('Record all three Zari voice samples before enrollment.');const auth=await serviceRpc('assurance_regent_browser_voice_enrollment_authorize',{p_user_id:userInput,p_password:password}),userId=String(auth?.user_id||'');if(!userId)throw new Error('Voice enrollment authorization failed.');const vectors=[],refs=[];for(let i=0;i<samples.length;i++){const bytes=decodeBase64(samples[i]?.audio_base64||'');if(!bytes.length||bytes.length>2_000_000)throw new Error(`Voice sample ${i+1} is invalid.`);const feat=voiceFeatureFromWav(bytes);vectors.push(feat.vector);refs.push(await uploadPrivateSample(userId,bytes,i));}const template=enrollmentTemplate(vectors),row={user_id:userId,template,sample_refs:refs,sample_count:vectors.length,phrase_version:1,active:true,enrolled_at:new Date().toISOString(),updated_at:new Date().toISOString(),failed_attempts:0};await serviceFetch(`/rest/v1/assurance_regent_voice_profiles?on_conflict=user_id`,{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});await audit('ENROLL',userId,true,template.self_similarity,ip_hash,{sample_count:vectors.length,threshold:template.threshold});return json({ok:true,user_id:userId,sample_count:vectors.length,quality:template.self_similarity,threshold:template.threshold});
    }
    if(mode==='challenge'){
      const phrase=challengePhrase(),requested=String(body?.claimed_user||'').trim().slice(0,120),expires=new Date(Date.now()+2*60*1000).toISOString();const rows=await insertRows('assurance_regent_voice_challenges',{phrase,requested_user:requested,ip_hash,expires_at:expires},true),challenge=rows?.[0];await audit('CHALLENGE','',true,null,ip_hash,{claimed:Boolean(requested)});return json({ok:true,challenge_id:challenge?.id,phrase,expires_at:expires});
    }
    if(mode==='verify'){
      const id=String(body?.challenge_id||''),bytes=decodeBase64(body?.audio_base64||'');if(!id||!bytes.length)throw new Error('Voice challenge and recording are required.');if(bytes.length>2_000_000)throw new Error('Voice verification recording is too large.');const rows=await selectRows('assurance_regent_voice_challenges',{select:'*',id:`eq.${id}`,limit:'1'}),challenge=rows?.[0];if(!challenge)throw new Error('Voice challenge is invalid.');if(Number(challenge.attempts||0)>=3)throw new Error('This voice challenge has reached its attempt limit. Start recognition again.');if(challenge.used_at||new Date(challenge.expires_at).getTime()<Date.now())throw new Error('Voice challenge has expired. Start recognition again.');if(challenge.ip_hash&&challenge.ip_hash!==ip_hash)throw new Error('Voice challenge must be completed from the same browser connection.');await patchRows('assurance_regent_voice_challenges',{id:`eq.${id}`},{attempts:Number(challenge.attempts||0)+1});const transcript=await transcribeWav(bytes);if(!transcriptMatches(transcript,challenge.phrase)){await audit('VERIFY','',false,0,ip_hash,{reason:'challenge_phrase_mismatch'});throw new Error('The spoken challenge phrase did not match. Please try voice recognition again.');}const feat=voiceFeatureFromWav(bytes),claimed=String(body?.claimed_user||challenge.requested_user||'').trim();let profiles=await selectRows('assurance_regent_voice_profiles',{select:'user_id,template,active',active:'eq.true',limit:'250'});if(!Array.isArray(profiles)||!profiles.length)throw new Error('No Zari voice profiles are enrolled yet.');if(claimed){const cred=await findCredential(claimed);if(!cred)throw new Error('No account matches the supplied username or email.');profiles=profiles.filter(p=>String(p.user_id)===String(cred.user_id));if(!profiles.length)throw new Error('This account does not have an enrolled Zari voice profile.');}
      const ranked=profiles.map(p=>({profile:p,score:cosine(feat.vector,p?.template?.centroid||[]),threshold:Number(p?.template?.threshold||.86)})).sort((a,b)=>b.score-a.score),best=ranked[0],second=ranked[1];const margin=best.score-(second?.score??-1),accepted=best.score>=best.threshold&&(claimed||!second||margin>=.025);if(!accepted){if(best?.profile?.user_id)await patchRows('assurance_regent_voice_profiles',{user_id:`eq.${best.profile.user_id}`},{failed_attempts:Number(best.profile.failed_attempts||0)+1,updated_at:new Date().toISOString()}).catch(()=>{});await audit('VERIFY',best?.profile?.user_id||'',false,best?.score??0,ip_hash,{threshold:best?.threshold||0,margin:Number(margin.toFixed(4)),claimed:Boolean(claimed)});throw new Error('Zari could not verify this voice with enough confidence. Use your password or try again in a quiet place.');}
      const userId=String(best.profile.user_id),login=await issueBrowserSession(userId,String(body?.requested_role||''));await patchRows('assurance_regent_voice_challenges',{id:`eq.${id}`},{used_at:new Date().toISOString()});await patchRows('assurance_regent_voice_profiles',{user_id:`eq.${userId}`},{last_verified_at:new Date().toISOString(),failed_attempts:0,updated_at:new Date().toISOString()});await audit('VERIFY',userId,true,best.score,ip_hash,{threshold:best.threshold,margin:Number(margin.toFixed(4)),claimed:Boolean(claimed)});return json({ok:true,...login,voice:{verified:true,score:Number(best.score.toFixed(4)),threshold:best.threshold,method:'speaker-template+dynamic-phrase'}});
    }
    return json({error:'Unknown Zari voice-access mode.'},400);
  }catch(error){console.error('Zari voice access error',error);return json({error:String(error?.message||error||'Voice access failed.')},400);}
});
