  /* Assurance Regent v6.3.116 — dashboard operational calendar holiday descriptions START */
  const DASHBOARD_HOLIDAY_DESCRIPTIONS_SCHEMA116='6.3.116',DASHBOARD_HOLIDAY_DESCRIPTION_EXAMPLE116='1 January - Holiday: New Year';
  function dashboardHolidayDescription116(row={}){
    if(typeof calendarHolidayDescription115==='function')return calendarHolidayDescription115(row.date||'',row.holidaySource||'');
    const raw=String(row.date||''),m=raw.match(/^(\d{4})-(\d{2})-(\d{2})$/u),months=['January','February','March','April','May','June','July','August','September','October','November','December'],date=m?`${Number(m[3])} ${months[Number(m[2])-1]||m[2]}`:raw,source=String(row.holidaySource||'Public Holiday'),official=source.match(/^Official public holiday\s*·\s*(.*?)\s*·/iu),name=String(official?.[1]||source||'Public Holiday').replace(/^New Year(?:'s|’s)? Day$/iu,'New Year');return `${date} - Holiday: ${name}`;
  }
  function dashboardHolidayRows116(){
    const prefix=String(state.month||'').slice(0,7),rows=(engine?.state?.calendar||[]).filter(x=>String(x.date||'').startsWith(prefix)&&String(x.dayType||'').toLowerCase().includes('holiday')).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))),seen=new Set(),out=[];
    for(const row of rows){const description=dashboardHolidayDescription116(row),key=`${String(row.date||'')}|${description}`;if(seen.has(key))continue;seen.add(key);out.push({...row,description});}return out;
  }
  function decorateDashboardHolidays116(){
    const host=$('dashMiniCalendar');if(!host)return false;const rows=dashboardHolidayRows116(),legend=host.querySelector('.mini-calendar-legend');let panel=host.querySelector('[data-dashboard-holiday-schedule116]');if(!panel){panel=document.createElement('section');panel.setAttribute('data-dashboard-holiday-schedule116','true');panel.setAttribute('aria-label','Holiday schedule');Object.assign(panel.style,{marginTop:'12px',paddingTop:'11px',borderTop:'1px solid #dce8ed'});if(legend)legend.insertAdjacentElement('afterend',panel);else host.appendChild(panel);}
    const country=String(window.AssuranceRegentCompanyHolidays?.context?.()?.countryName||'').trim(),head=document.createElement('div'),title=document.createElement('strong'),hint=document.createElement('small'),list=document.createElement('div');head.setAttribute('data-dashboard-holiday-head116','true');Object.assign(head.style,{display:'flex',alignItems:'baseline',justifyContent:'space-between',gap:'10px',marginBottom:'7px'});title.textContent='Holiday schedule';Object.assign(title.style,{fontSize:'12px',color:'#173746'});hint.textContent=country?`Public holidays · ${country}`:'Public holidays';Object.assign(hint.style,{fontSize:'10px',color:'#708994',textAlign:'right'});head.append(title,hint);list.setAttribute('data-dashboard-holiday-list116','true');Object.assign(list.style,{display:'grid',gap:'5px',maxHeight:'128px',overflowY:'auto',paddingRight:'3px'});
    if(rows.length){for(const row of rows){const item=document.createElement('div'),dot=document.createElement('i'),text=document.createElement('span'),day=Number(String(row.date||'').slice(-2));item.setAttribute('data-dashboard-holiday-date116',String(row.date||''));Object.assign(item.style,{display:'flex',alignItems:'flex-start',gap:'8px',padding:'6px 8px',borderRadius:'8px',background:'#fffaf0',fontSize:'11px',lineHeight:'1.35',color:'#274552'});dot.className='holiday-dot';Object.assign(dot.style,{marginTop:'4px',flex:'0 0 auto'});text.textContent=row.description;item.append(dot,text);list.appendChild(item);const button=host.querySelector(`[data-calendar-day="${day}"]`);if(button){button.dataset.holidayDescription116=row.description;button.title=row.description;button.setAttribute('aria-label',row.description);button.addEventListener('click',()=>{item.scrollIntoView?.({block:'nearest',behavior:'smooth'});const before=item.style.boxShadow;item.style.boxShadow='0 0 0 2px rgba(210,145,30,.28)';setTimeout(()=>{item.style.boxShadow=before;},900);},{once:false});}}
    }else{const empty=document.createElement('div');empty.textContent=`No public holidays listed for ${window.ADRAEngine?.monthLabel?.(state.month)||'this month'}.`;Object.assign(empty.style,{fontSize:'11px',color:'#708994',padding:'5px 0'});list.appendChild(empty);}
    panel.replaceChildren(head,list);panel.dataset.holidayCount116=String(rows.length);return true;
  }
  const renderDashboardCalendarBefore116=renderDashboardCalendar;
  renderDashboardCalendar=function(monthRows){const value=renderDashboardCalendarBefore116(monthRows);decorateDashboardHolidays116();return value;};
  function refreshDashboardHolidayDescriptions116(){if(state.view!=='dashboard'||!$('dashMiniCalendar'))return false;const prefix=String(state.month||'').slice(0,7),monthRows=scopeMtsRows(state.mtsSessions||[]).filter(x=>String(x.work_date||'').startsWith(prefix));renderDashboardCalendar(monthRows);return true;}
  window.addEventListener('assurance-regent-company-country-saved',()=>setTimeout(refreshDashboardHolidayDescriptions116,180));window.addEventListener('assurance-regent-session-ready',()=>setTimeout(refreshDashboardHolidayDescriptions116,260));
  window.AssuranceRegentDashboardHolidayDescriptions={schema:DASHBOARD_HOLIDAY_DESCRIPTIONS_SCHEMA116,format:'D Month - Holiday: Name',example:DASHBOARD_HOLIDAY_DESCRIPTION_EXAMPLE116,visibleSchedule:true,dayTooltips:true,countryAware:true,technicalMetadataPreserved:true,refresh:refreshDashboardHolidayDescriptions116};
  queueMicrotask(()=>{try{if($('dashMiniCalendar'))decorateDashboardHolidays116();}catch{}});
  /* Assurance Regent v6.3.116 — dashboard operational calendar holiday descriptions END */
