  /* Assurance Regent v6.3.116 — dashboard operational calendar holiday descriptions START */
  const DASHBOARD_HOLIDAY_DESCRIPTIONS_SCHEMA116='6.3.116',DASHBOARD_HOLIDAY_DESCRIPTION_EXAMPLE116='1 January - Holiday: New Year',DASHBOARD_HOLIDAY_LEGEND_EXAMPLE116="Monday, 3 August - Holiday: Farmers' Day";
  function dashboardHolidayDateParts116(value=''){
    const raw=String(value||'').trim(),m=raw.match(/^(\d{4})-(\d{2})-(\d{2})$/u);if(!m)return {dateLabel:raw,weekday:''};
    const months=['January','February','March','April','May','June','July','August','September','October','November','December'],date=new Date(`${raw}T12:00:00`),weekday=Number.isNaN(date.getTime())?'':date.toLocaleDateString('en-US',{weekday:'long'}),dateLabel=`${Number(m[3])} ${months[Number(m[2])-1]||m[2]}`;return {dateLabel,weekday};
  }
  function dashboardHolidayName116(source=''){
    const raw=String(source||'Public Holiday').trim(),official=raw.match(/^Official public holiday\s*·\s*(.*?)\s*·/iu);return String(official?.[1]||raw||'Public Holiday').replace(/^New Year(?:'s|’s)? Day$/iu,'New Year').trim()||'Public Holiday';
  }
  function dashboardHolidayDescription116(row={}){
    const parts=dashboardHolidayDateParts116(row.date||''),name=dashboardHolidayName116(row.holidaySource||''),date=parts.weekday?`${parts.weekday}, ${parts.dateLabel}`:parts.dateLabel;return `${date} - Holiday: ${name}`;
  }
  function dashboardHolidayRows116(){
    const prefix=String(state.month||'').slice(0,7),rows=(engine?.state?.calendar||[]).filter(x=>String(x.date||'').startsWith(prefix)&&String(x.dayType||'').toLowerCase().includes('holiday')).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))),seen=new Set(),out=[];
    for(const row of rows){const description=dashboardHolidayDescription116(row),key=`${String(row.date||'')}|${description}`;if(seen.has(key))continue;seen.add(key);out.push({...row,description,holidayName:dashboardHolidayName116(row.holidaySource||'')});}return out;
  }
  function dashboardHolidayLegend116(host){
    const legend=host?.querySelector('.mini-calendar-legend');if(!legend)return null;const spans=[...legend.querySelectorAll('span')],holiday=spans.find(x=>x.querySelector('.holiday-dot'));
    if(holiday){let label=holiday.querySelector('[data-dashboard-holiday-legend-label116]');if(!label){holiday.childNodes.forEach(node=>{if(node.nodeType===Node.TEXT_NODE)node.textContent='';});label=document.createElement('span');label.setAttribute('data-dashboard-holiday-legend-label116','true');holiday.appendChild(label);}label.textContent='Holiday — details listed below';holiday.title='Public holidays for the selected month are listed below with weekday, date and holiday name.';}
    return legend;
  }
  function decorateDashboardHolidays116(){
    const host=$('dashMiniCalendar');if(!host)return false;const rows=dashboardHolidayRows116(),legend=dashboardHolidayLegend116(host);let panel=host.querySelector('[data-dashboard-holiday-schedule116]');if(!panel){panel=document.createElement('section');panel.setAttribute('data-dashboard-holiday-schedule116','true');panel.setAttribute('aria-label','Holiday schedule');Object.assign(panel.style,{marginTop:'12px',paddingTop:'11px',borderTop:'1px solid #dce8ed'});if(legend)legend.insertAdjacentElement('afterend',panel);else host.appendChild(panel);}
    const country=String(window.AssuranceRegentCompanyHolidays?.context?.()?.countryName||'').trim(),monthLabel=window.ADRAEngine?.monthLabel?.(state.month)||'Selected month',head=document.createElement('div'),title=document.createElement('strong'),hint=document.createElement('small'),list=document.createElement('div');head.setAttribute('data-dashboard-holiday-head116','true');Object.assign(head.style,{display:'flex',alignItems:'baseline',justifyContent:'space-between',gap:'10px',marginBottom:'7px'});title.textContent=`Holiday — ${monthLabel}`;Object.assign(title.style,{fontSize:'12px',color:'#173746'});hint.textContent=rows.length?`${rows.length} public holiday${rows.length===1?'':'s'}${country?` · ${country}`:''}`:(country?`Public holidays · ${country}`:'Public holidays');Object.assign(hint.style,{fontSize:'10px',color:'#708994',textAlign:'right'});head.append(title,hint);list.setAttribute('data-dashboard-holiday-list116','true');Object.assign(list.style,{display:'grid',gap:'5px',maxHeight:'148px',overflowY:'auto',paddingRight:'3px'});
    if(rows.length){for(const row of rows){const item=document.createElement('div'),dot=document.createElement('i'),textWrap=document.createElement('span'),text=document.createElement('strong'),kind=document.createElement('small'),day=Number(String(row.date||'').slice(-2));item.setAttribute('data-dashboard-holiday-date116',String(row.date||''));Object.assign(item.style,{display:'flex',alignItems:'flex-start',gap:'8px',padding:'7px 8px',borderRadius:'8px',background:'#fffaf0',fontSize:'11px',lineHeight:'1.35',color:'#274552'});dot.className='holiday-dot';Object.assign(dot.style,{marginTop:'5px',flex:'0 0 auto'});Object.assign(textWrap.style,{display:'grid',gap:'1px'});text.textContent=row.description;Object.assign(text.style,{fontSize:'11px',fontWeight:'650'});kind.textContent='Official public holiday';Object.assign(kind.style,{fontSize:'10px',color:'#7d6a42'});textWrap.append(text,kind);item.append(dot,textWrap);list.appendChild(item);const button=host.querySelector(`[data-calendar-day="${day}"]`);if(button){button.dataset.holidayDescription116=row.description;button.title=row.description;button.setAttribute('aria-label',row.description);button.addEventListener('click',()=>{item.scrollIntoView?.({block:'nearest',behavior:'smooth'});const before=item.style.boxShadow;item.style.boxShadow='0 0 0 2px rgba(210,145,30,.28)';setTimeout(()=>{item.style.boxShadow=before;},900);},{once:false});}}
    }else{const empty=document.createElement('div');empty.textContent=`No public holidays listed for ${monthLabel}.`;Object.assign(empty.style,{fontSize:'11px',color:'#708994',padding:'5px 0'});list.appendChild(empty);}
    panel.replaceChildren(head,list);panel.dataset.holidayCount116=String(rows.length);return true;
  }
  const renderDashboardCalendarBefore116=renderDashboardCalendar;
  renderDashboardCalendar=function(monthRows){const value=renderDashboardCalendarBefore116(monthRows);decorateDashboardHolidays116();return value;};
  function refreshDashboardHolidayDescriptions116(){if(state.view!=='dashboard'||!$('dashMiniCalendar'))return false;const prefix=String(state.month||'').slice(0,7),monthRows=scopeMtsRows(state.mtsSessions||[]).filter(x=>String(x.work_date||'').startsWith(prefix));renderDashboardCalendar(monthRows);return true;}
  window.addEventListener('assurance-regent-company-country-saved',()=>setTimeout(refreshDashboardHolidayDescriptions116,180));window.addEventListener('assurance-regent-session-ready',()=>setTimeout(refreshDashboardHolidayDescriptions116,260));
  window.AssuranceRegentDashboardHolidayDescriptions={schema:DASHBOARD_HOLIDAY_DESCRIPTIONS_SCHEMA116,format:'Weekday, D Month - Holiday: Name',example:DASHBOARD_HOLIDAY_LEGEND_EXAMPLE116,visibleSchedule:true,legendExplainsDetails:true,weekdayIncluded:true,holidayKindIncluded:true,dayTooltips:true,countryAware:true,technicalMetadataPreserved:true,refresh:refreshDashboardHolidayDescriptions116};
  queueMicrotask(()=>{try{if($('dashMiniCalendar'))decorateDashboardHolidays116();}catch{}});
  /* Assurance Regent v6.3.116 — dashboard operational calendar holiday descriptions END */
