  /* Assurance Regent v6.3.59 — LinkedIn-style inline Department Hub video START */
  let companyHubInlineVideoObserver59=null,companyHubInlineVideoMutation59=null,companyHubInlineVideoBound59=false;
  const companyHubInlineVideoRatios59=new WeakMap(),companyHubInlineVideoInternalPause59=new WeakSet();
  function companyHubInlineVideos59(){return [...document.querySelectorAll('.company-social-media.video video')];}
  function companyHubPauseInlineVideo59(video){if(!video||video.paused)return;companyHubInlineVideoInternalPause59.add(video);try{video.pause();}finally{queueMicrotask(()=>companyHubInlineVideoInternalPause59.delete(video));}}
  function companyHubPauseOtherInlineVideos59(active){for(const video of companyHubInlineVideos59())if(video!==active)companyHubPauseInlineVideo59(video);}
  function companyHubPrepareInlineVideo59(video){if(!video||video.dataset.companyHubInlineVideo59==='true')return;video.dataset.companyHubInlineVideo59='true';video.controls=true;video.playsInline=true;video.preload='metadata';video.muted=true;video.defaultMuted=true;video.setAttribute('muted','');video.setAttribute('playsinline','');video.setAttribute('controls','');video.removeAttribute('autoplay');video.addEventListener('play',()=>{companyHubPauseOtherInlineVideos59(video);});video.addEventListener('pause',()=>{if(companyHubInlineVideoInternalPause59.has(video))return;const ratio=Number(companyHubInlineVideoRatios59.get(video)||0);if(ratio>=.6&&!video.ended)video.dataset.companyHubManualPause59='true';});video.addEventListener('ended',()=>{video.dataset.companyHubManualPause59='true';});companyHubInlineVideoObserver59?.observe(video);}
  function companyHubAutoplayBestVisibleVideo59(){if(document.hidden||!document.body.classList.contains('department-hub-social-mode')){for(const video of companyHubInlineVideos59())companyHubPauseInlineVideo59(video);return;}const candidates=companyHubInlineVideos59().filter(v=>Number(companyHubInlineVideoRatios59.get(v)||0)>=.62&&v.dataset.companyHubManualPause59!=='true'&&!v.ended);candidates.sort((a,b)=>Number(companyHubInlineVideoRatios59.get(b)||0)-Number(companyHubInlineVideoRatios59.get(a)||0));const best=candidates[0]||null;for(const video of companyHubInlineVideos59())if(video!==best&&Number(companyHubInlineVideoRatios59.get(video)||0)<.28)companyHubPauseInlineVideo59(video);if(!best)return;companyHubPauseOtherInlineVideos59(best);if(best.paused){best.muted=true;best.defaultMuted=true;best.play().catch(()=>{});}}
  function companyHubObserveInlineVideos59(){for(const video of companyHubInlineVideos59())companyHubPrepareInlineVideo59(video);document.querySelectorAll('.company-hub-inline-video-open,[data-company-inline-video]').forEach(node=>node.remove());companyHubAutoplayBestVisibleVideo59();}
  function renderCompanyHubInlineVideo59(){queueMicrotask(companyHubObserveInlineVideos59);setTimeout(companyHubObserveInlineVideos59,140);}
  function bindCompanyHubInlineVideo59(){if(companyHubInlineVideoBound59)return;companyHubInlineVideoBound59=true;companyHubInlineVideoObserver59=new IntersectionObserver(entries=>{for(const entry of entries){const video=entry.target;companyHubInlineVideoRatios59.set(video,entry.intersectionRatio||0);if(entry.intersectionRatio<.22)companyHubPauseInlineVideo59(video);}companyHubAutoplayBestVisibleVideo59();},{threshold:[0,.22,.4,.62,.8,1]});companyHubInlineVideoMutation59=new MutationObserver(()=>{if(document.body.classList.contains('department-hub-social-mode'))queueMicrotask(companyHubObserveInlineVideos59);});companyHubInlineVideoMutation59.observe(document.body,{subtree:true,childList:true});document.addEventListener('visibilitychange',companyHubAutoplayBestVisibleVideo59);document.addEventListener('click',e=>{const video=e.target.closest?.('.company-social-media.video video');if(!video)return;video.dataset.companyHubManualPause59='';});renderCompanyHubInlineVideo59();}
  /* Assurance Regent v6.3.59 — LinkedIn-style inline Department Hub video END */
