  /* Assurance Regent v6.3.62 — slideshow statuses and algorithmic trending START */
  const COMPANY_HUB_STATUS_MAX_ATTACHMENTS62=4;
  const COMPANY_HUB_STATUS_EFFECTS62=['fade','slide','zoom','kenburns','none'];
  const companyHubStatusPresentationCache62=new Map(),companyHubStatusPresentationLoading62=new Map(),companyHubViewedThisSession62=new Set(),companyHubViewTimers62=new Map();
  let companyHubStorySlideTimer62=null,companyHubPostViewObserver62=null,companyHubTrendingRows62=[],companyHubTrendingLoading62=false,companyHubTrendingCompany62='',companyHubTrendingRefreshTimer62=null;
  try{READ_RPC_NAMES.add('assurance_regent_browser_department_status_presentation_get');READ_RPC_NAMES.add('assurance_regent_browser_department_social_trending');RPC_CACHE_TTL.assurance_regent_browser_department_status_presentation_get=12000;RPC_CACHE_TTL.assurance_regent_browser_department_social_trending=8000;}catch{}

  function companyHubStatusPresentation62(status={}){const id=String(status.id||''),cached=companyHubStatusPresentationCache62.get(id)||status.presentation||{};const effect=COMPANY_HUB_STATUS_EFFECTS62.includes(String(cached.effect||'').toLowerCase())?String(cached.effect).toLowerCase():'fade',slideSeconds=Math.max(2,Math.min(12,Number(cached.slideSeconds||5)));return {effect,slideSeconds};}
  async function companyHubLoadStatusPresentation62(status={}){const id=String(status.id||'');if(!id)return {effect:'fade',slideSeconds:5};if(companyHubStatusPresentationCache62.has(id))return companyHubStatusPresentationCache62.get(id);if(companyHubStatusPresentationLoading62.has(id))return companyHubStatusPresentationLoading62.get(id);const work=(async()=>{try{const p=await supabaseRpc('assurance_regent_browser_department_status_presentation_get',{p_token:browserSessionToken,p_message_id:id,p_company_id:departmentHubContextCompanyId()},{bypassCache:false});const value=companyHubStatusPresentation62({...status,presentation:p||{}});companyHubStatusPresentationCache62.set(id,value);return value;}catch{const value={effect:'fade',slideSeconds:5};companyHubStatusPresentationCache62.set(id,value);return value;}finally{companyHubStatusPresentationLoading62.delete(id);}})();companyHubStatusPresentationLoading62.set(id,work);return work;}
  function companyHubStorySelectedMedia62(dlg){const media=[...(dlg?.querySelector('[data-company-story-media]')?.files||[])],music=dlg?.querySelector('[data-company-story-music]')?.files?.[0]||null;return {media,music,total:media.length+(music?1:0)};}

  companyHubStoryComposeDialog=function(){let dlg=document.getElementById('companyHubStoryComposeDialog');if(dlg&&!dlg.dataset.storyV62){try{dlg.close();}catch{}dlg.remove();dlg=null;}if(dlg)return dlg;dlg=document.createElement('dialog');dlg.id='companyHubStoryComposeDialog';dlg.dataset.storyV62='true';dlg.className='company-hub-story-compose-dialog';dlg.innerHTML='<form class="company-hub-story-compose-card" data-company-story-compose-form><div class="company-hub-modal-head"><h3>Create status</h3><button type="button" class="company-hub-modal-close" data-company-story-compose-close>×</button></div><div class="company-hub-story-compose-body"><div data-company-story-author></div><textarea data-company-story-text maxlength="1000" placeholder="Share a thought, update or moment…"></textarea><div class="company-hub-story-tools"><label class="company-hub-story-tool">🖼 Photos / video<input type="file" data-company-story-media accept="image/*,video/*" multiple /></label><label class="company-hub-story-tool">🎵 Add song<input type="file" data-company-story-music accept="audio/*" /></label></div><div class="company-hub-story-presentation-tools"><label>Transition effect<select data-company-story-effect><option value="fade">Fade</option><option value="slide">Slide</option><option value="zoom">Zoom</option><option value="kenburns">Photo motion</option><option value="none">None</option></select></label><label>Slide pace<select data-company-story-slide-seconds><option value="3">3 seconds</option><option value="5" selected>5 seconds</option><option value="7">7 seconds</option><option value="10">10 seconds</option></select></label></div><small class="company-hub-story-selection-note">Use several photos to create a slideshow. A song can play across the slideshow. Up to four combined media/music attachments per status.</small><div class="company-hub-story-selected" data-company-story-selected></div><div class="company-hub-story-emoji-row">'+COMPANY_HUB_STORY_EMOJIS.map(e=>`<button type="button" data-company-story-compose-emoji="${e}">${e}</button>`).join('')+'</div></div><div class="company-hub-modal-actions"><button type="button" class="btn ghost small" data-company-story-compose-close>Cancel</button><button type="submit" class="company-hub-modal-submit">Share status</button></div></form>';dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close();});document.body.appendChild(dlg);return dlg;};
  previewCompanyHubStoryFiles=function(dlg){const {media,music,total}=companyHubStorySelectedMedia62(dlg),host=dlg?.querySelector('[data-company-story-selected]');if(!host)return;const rows=[...media.map((f,i)=>`<span><b>${media.length>1?`Slide ${i+1} · `:''}${esc(f.name)}</b><small>${Math.max(1,Math.round(f.size/1024))} KB · ${f.type.startsWith('video/')?'video':'photo'}</small></span>`),music?`<span><b>🎵 ${esc(music.name)}</b><small>${Math.max(1,Math.round(music.size/1024))} KB · soundtrack</small></span>`:''];if(total>COMPANY_HUB_STATUS_MAX_ATTACHMENTS62)rows.push(`<span><b>Too many attachments</b><small>Choose no more than ${COMPANY_HUB_STATUS_MAX_ATTACHMENTS62} combined photos/videos/song files.</small></span>`);host.innerHTML=rows.join('');};
  submitCompanyHubStory=async function(form){const dlg=form.closest('dialog'),text=String(form.querySelector('[data-company-story-text]')?.value||'').trim(),{media,music,total}=companyHubStorySelectedMedia62(dlg),effect=String(form.querySelector('[data-company-story-effect]')?.value||'fade'),slideSeconds=Number(form.querySelector('[data-company-story-slide-seconds]')?.value||5),companyId=departmentHubContextCompanyId();if(!text&&!total)return toast('Write a status or add photo, video or music.');if(total>COMPANY_HUB_STATUS_MAX_ATTACHMENTS62)return toast(`A status can contain up to ${COMPANY_HUB_STATUS_MAX_ATTACHMENTS62} combined media/music files.`);const submit=form.querySelector('button[type="submit"]');if(submit)submit.disabled=true;try{const stored=[];for(const file of media)stored.push(await uploadPersistentFile(file,{category:'department-social-status',entityType:'department-social-status',entityId:'Company Lounge',companyId,metadata:{mediaRole:'story-media',status:true,slideshow:media.length>1}}));if(music)stored.push(await uploadPersistentFile(music,{category:'department-social-status',entityType:'department-social-status',entityId:'Company Lounge',companyId,metadata:{mediaRole:'story-music',status:true,soundtrack:true}}));const created=await supabaseRpc('assurance_regent_browser_department_social_post',{p_token:browserSessionToken,p_department:'Company Lounge',p_content:text,p_post_kind:'STATUS',p_attachment_file_ids:stored.map(x=>x.fileId),p_parent_id:null,p_company_id:companyId},{bypassCache:true});if(created?.id){const presentation={effect:COMPANY_HUB_STATUS_EFFECTS62.includes(effect)?effect:'fade',slideSeconds:Math.max(2,Math.min(12,slideSeconds))};companyHubStatusPresentationCache62.set(String(created.id),presentation);await supabaseRpc('assurance_regent_browser_department_status_presentation_set',{p_token:browserSessionToken,p_message_id:created.id,p_effect:presentation.effect,p_slide_seconds:presentation.slideSeconds,p_company_id:companyId},{bypassCache:true}).catch(err=>console.warn('Status presentation could not be saved:',err));}dlg?.close();await loadCompanyHubMessages(state.companyHubDepartment||'Company Lounge',true);const me=String(controlUser()?.id||''),rows=companyHubStatusGroups().get(me)||[];if(rows.length)openCompanyHubStory(me,rows.length-1);}catch(err){toast(err.message||'Could not share this status.');}finally{if(submit)submit.disabled=false;}};

  companyHubStoryMediaMarkup=function(status){const atts=Array.isArray(status.attachments)?status.attachments:[],visual=atts.filter(a=>/^image\//i.test(String(a.mimeType||''))||/^video\//i.test(String(a.mimeType||''))),audio=atts.find(a=>/^audio\//i.test(String(a.mimeType||'')))||null,other=atts.filter(a=>!visual.includes(a)&&a!==audio),presentation=companyHubStatusPresentation62(status),slides=visual.map((a,i)=>`<div class="company-hub-story-slide ${i===0?'active':''}" data-company-story-slide="${i}" aria-hidden="${i===0?'false':'true'}">${companySocialAttachments([a])}</div>`).join(''),dots=visual.length>1?`<div class="company-hub-story-slide-dots" aria-label="Status slideshow">${visual.map((_,i)=>`<button type="button" class="${i===0?'active':''}" data-company-story-slide-dot="${i}" aria-label="Show slide ${i+1}"></button>`).join('')}</div>`:'',sound=audio?`<div class="company-hub-story-soundtrack" data-company-story-audio="${esc(audio.fileId||'')}"><b>🎵 ${esc(audio.name||'Soundtrack')}</b><span>Loading song…</span></div>`:'';return `${visual.length?`<div class="company-hub-story-slideshow effect-${esc(presentation.effect)}" data-company-story-slideshow data-story-effect="${esc(presentation.effect)}" data-story-seconds="${presentation.slideSeconds}" style="--story-slide-ms:${presentation.slideSeconds*1000}ms">${slides}${dots}${sound}</div>`:sound}${other.map(a=>`<div class="company-hub-story-media">${companySocialAttachments([a])}</div>`).join('')}`;};

  const companyHubHydrateStoryMediaBase62=hydrateCompanyHubStoryMedia;
  hydrateCompanyHubStoryMedia=async function(){await companyHubHydrateStoryMediaBase62();for(const node of document.querySelectorAll('.company-hub-story-soundtrack[data-company-story-audio]')){const audio=node.querySelector('audio');if(audio){audio.loop=true;audio.preload='metadata';audio.volume=.78;audio.play().catch(()=>{});}}companyHubInitStorySlideshow62();};
  function companyHubStopStorySlideshow62(){if(companyHubStorySlideTimer62){clearInterval(companyHubStorySlideTimer62);companyHubStorySlideTimer62=null;}}
  function companyHubShowStorySlide62(box,index){const slides=[...box.querySelectorAll('[data-company-story-slide]')],dots=[...box.querySelectorAll('[data-company-story-slide-dot]')];if(!slides.length)return;const next=((Number(index)||0)%slides.length+slides.length)%slides.length;slides.forEach((slide,i)=>{slide.classList.toggle('active',i===next);slide.setAttribute('aria-hidden',i===next?'false':'true');const video=slide.querySelector('video');if(video&&i!==next)video.pause();});dots.forEach((dot,i)=>dot.classList.toggle('active',i===next));box.dataset.storySlideIndex=String(next);}
  function companyHubInitStorySlideshow62(){companyHubStopStorySlideshow62();const dlg=document.getElementById('companyHubStoryViewerDialog'),box=dlg?.querySelector('[data-company-story-slideshow]');if(!box)return;const slides=[...box.querySelectorAll('[data-company-story-slide]')];companyHubShowStorySlide62(box,Number(box.dataset.storySlideIndex||0));for(const dot of box.querySelectorAll('[data-company-story-slide-dot]'))dot.onclick=e=>{e.preventDefault();companyHubShowStorySlide62(box,Number(dot.dataset.companyStorySlideDot||0));companyHubInitStorySlideshow62();};if(slides.length>1){const seconds=Math.max(2,Math.min(12,Number(box.dataset.storySeconds||5)));companyHubStorySlideTimer62=setInterval(()=>{const current=Number(box.dataset.storySlideIndex||0),active=slides[current],video=active?.querySelector('video');if(video&&!video.paused&&!video.ended)return;companyHubShowStorySlide62(box,current+1);},seconds*1000);}}
  function companyHubFitStoryText62(){const dlg=document.getElementById('companyHubStoryViewerDialog'),content=dlg?.querySelector('.company-hub-story-content'),p=content?.querySelector(':scope > p');if(!content)return;const hasMedia=Boolean(content.querySelector('[data-company-story-slideshow],.company-hub-story-media,.company-hub-story-soundtrack'));content.classList.toggle('story-text-only',!hasMedia);if(!p)return;const len=(p.textContent||'').trim().length;p.classList.remove('story-text-short','story-text-medium','story-text-long','story-text-dense');p.classList.add(len<=90?'story-text-short':len<=260?'story-text-medium':len<=560?'story-text-long':'story-text-dense');requestAnimationFrame(()=>{let px=len<=90?30:len<=260?22:len<=560?16:12,min=9,cap=hasMedia?Math.max(72,Math.min(180,content.clientHeight*.3)):Math.max(120,content.clientHeight*.76);p.style.setProperty('font-size',`${px}px`,'important');while(px>min&&p.scrollHeight>cap){px-=1;p.style.setProperty('font-size',`${px}px`,'important');}});}

  async function companyHubRecordView62(messageId){const id=String(messageId||''),companyId=departmentHubContextCompanyId(),key=`${companyId}|${id}`;if(!id||!companyId||companyHubViewedThisSession62.has(key))return;companyHubViewedThisSession62.add(key);try{await supabaseRpc('assurance_regent_browser_department_social_view',{p_token:browserSessionToken,p_message_id:id,p_company_id:companyId},{bypassCache:true});clearTimeout(companyHubTrendingRefreshTimer62);companyHubTrendingRefreshTimer62=setTimeout(()=>companyHubLoadTrending62(true),700);}catch{companyHubViewedThisSession62.delete(key);}}

  const renderCompanyHubStoryViewerBase62=renderCompanyHubStoryViewer;
  renderCompanyHubStoryViewer=function(){renderCompanyHubStoryViewerBase62();companyHubStopStorySlideshow62();requestAnimationFrame(()=>{companyHubFitStoryText62();companyHubInitStorySlideshow62();});const st=companyHubStoryViewerState,rows=st?(companyHubStatusGroups().get(String(st.ownerId||''))||[]):[],status=rows[Math.max(0,Math.min(Number(st?.index||0),rows.length-1))];if(status){if(st)st.statusId=String(status.id||'');companyHubRecordView62(status.id);if(!companyHubStatusPresentationCache62.has(String(status.id||'')))companyHubLoadStatusPresentation62(status).then(()=>{const cur=companyHubStoryViewerState;if(cur&&String(cur.statusId||'')===String(status.id||''))renderCompanyHubStoryViewer();});}};
  openCompanyHubStory=function(ownerId,index=0){const groups=companyHubStatusGroups(),rows=groups.get(String(ownerId||''))||[];if(!rows.length){if(String(ownerId||'')===String(controlUser()?.id||''))renderCompanyHubStoryCompose();return;}companyHubStoryViewerState={ownerId:String(ownerId),index:Number(index||0),statusId:String(rows[Math.max(0,Math.min(Number(index||0),rows.length-1))]?.id||'')};const dlg=companyHubStoryViewerDialog();renderCompanyHubStoryViewer();if(!dlg.open)dlg.showModal();};

  function companyHubBindPostViewObserver62(){if(companyHubPostViewObserver62)companyHubPostViewObserver62.disconnect();for(const timer of companyHubViewTimers62.values())clearTimeout(timer);companyHubViewTimers62.clear();if(!('IntersectionObserver'in window)||!document.body.classList.contains('department-hub-social-mode'))return;companyHubPostViewObserver62=new IntersectionObserver(entries=>{for(const entry of entries){const id=String(entry.target?.dataset?.socialPostCard||'');if(!id)continue;if(entry.isIntersecting&&entry.intersectionRatio>=.62){if(companyHubViewTimers62.has(id))continue;companyHubViewTimers62.set(id,setTimeout(()=>{companyHubViewTimers62.delete(id);if(entry.target?.isConnected)companyHubRecordView62(id);},1200));}else{const timer=companyHubViewTimers62.get(id);if(timer)clearTimeout(timer);companyHubViewTimers62.delete(id);}}},{root:document.querySelector('.company-social-main')||null,threshold:[0,.35,.62,.8,1]});for(const card of document.querySelectorAll('[data-social-post-card]'))companyHubPostViewObserver62.observe(card);}

  function companyHubTrendingHost62(){const news=companyHubProjectNewsHost?.();if(!news)return null;let host=news.querySelector('#companyHubTrending62');if(!host){host=document.createElement('section');host.id='companyHubTrending62';host.className='company-hub-trending';news.appendChild(host);}return host;}
  function companyHubTrendingAuthor62(row={}){const p=companyHubSocialLayerPerson(row.senderId)||{},name=String(p.name||row.senderName||row.senderId||'Colleague'),role=String(p.position||p.department||row.department||'Company member');return {p,name,role};}
  function companyHubRenderTrending62(){const host=companyHubTrendingHost62();if(!host)return;const row=companyHubTrendingRows62[0];if(!row){host.innerHTML='<div class="company-hub-trending-head"><div><small>Social analytics</small><h4>Trending now</h4></div></div><div class="company-hub-trending-empty">Trend analytics will appear as colleagues view, react to and discuss Department Hub posts.</div>';return;}const {p,name,role}=companyHubTrendingAuthor62(row),score=Number(row.trendScore||0),views=Number(row.viewCount||0),impressions=Number(row.impressions||0),reactions=Number(row.reactions||0),comments=Number(row.comments||0),contributors=Number(row.contributors||0),copy=String(row.content||'Department Hub update').trim()||'Department Hub update';host.innerHTML=`<div class="company-hub-trending-head"><div><small>Social analytics</small><h4>Trending now</h4></div><span class="company-hub-trending-badge">${esc(row.trendLabel||'New')}</span></div><button type="button" class="company-hub-trending-card" data-company-trending-open="${esc(row.id||'')}"><div class="company-hub-trending-author">${companySocialAvatar(p,'small')}<span><b>${esc(name)}</b><small>${esc(role)} · ${esc(row.postKind==='PROJECT_NEWS'?'Project News':row.department||'Department Hub')}</small></span></div><p class="company-hub-trending-copy">${esc(copy)}</p><div class="company-hub-trending-analytics"><span><b>${score.toFixed(1)}</b><small>Trend score</small></span><span><b>${views}</b><small>Viewers</small></span><span><b>${impressions}</b><small>Views</small></span><span><b>${reactions}</b><small>Reactions</small></span><span><b>${comments}</b><small>Comments</small></span><span><b>${contributors}</b><small>Contributors</small></span></div><small class="company-hub-trending-method">Momentum ranking combines recent viewership, repeat views, reactions, conversation activity, contributors and freshness.</small></button>`;}
  async function companyHubLoadTrending62(force=false){const companyId=departmentHubContextCompanyId();if(!companyId||companyHubTrendingLoading62)return;if(!force&&companyHubTrendingCompany62===companyId&&companyHubTrendingRows62.length){companyHubRenderTrending62();return;}companyHubTrendingLoading62=true;try{const rows=await supabaseRpc('assurance_regent_browser_department_social_trending',{p_token:browserSessionToken,p_company_id:companyId,p_limit:5},{bypassCache:force});companyHubTrendingRows62=Array.isArray(rows)?rows:[];companyHubTrendingCompany62=companyId;companyHubRenderTrending62();}catch(err){console.warn('Department Hub trending analytics unavailable:',err);companyHubRenderTrending62();}finally{companyHubTrendingLoading62=false;}}
  function companyHubOpenTrending62(id){const row=companyHubTrendingRows62.find(x=>String(x.id||'')===String(id||''));if(!row)return;if(String(row.postKind||'').toUpperCase()==='PROJECT_NEWS'){companyHubRecordView62(row.id);openCompanyHubProjectNews?.(row.id);return;}const jump=()=>document.querySelector(`[data-social-post-card="${CSS.escape(String(row.id||''))}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});if(document.querySelector(`[data-social-post-card="${CSS.escape(String(row.id||''))}"]`)){jump();return;}const dep=String(row.department||'Company Lounge'),button=[...document.querySelectorAll('[data-company-hub-department]')].find(b=>companyHubDecodeDepartment53?.(b.dataset.companyHubDepartment)===dep||decodeURIComponent(String(b.dataset.companyHubDepartment||''))===dep);if(button){button.click();setTimeout(jump,650);}}
  function renderCompanyHubStoriesTrending62(){companyHubRenderTrending62();companyHubBindPostViewObserver62();companyHubLoadTrending62(false);}

  if(typeof companyHubRenderProjectNewsPaged53==='function'&&!window.__assuranceRegentProjectNewsTrendWrap62){window.__assuranceRegentProjectNewsTrendWrap62=true;const base=companyHubRenderProjectNewsPaged53;companyHubRenderProjectNewsPaged53=function(...args){const out=base(...args);queueMicrotask(()=>companyHubRenderTrending62());return out;};}
  if(!window.__assuranceRegentStoryTrendEvents62){window.__assuranceRegentStoryTrendEvents62=true;document.addEventListener('click',e=>{const trend=e.target.closest?.('[data-company-trending-open]');if(trend){e.preventDefault();e.stopPropagation();companyHubOpenTrending62(trend.dataset.companyTrendingOpen);return;}const news=e.target.closest?.('[data-company-project-news-open]');if(news)companyHubRecordView62(news.dataset.companyProjectNewsOpen);},true);document.addEventListener('close',e=>{if(e.target?.id==='companyHubStoryViewerDialog'){companyHubStopStorySlideshow62();e.target.querySelectorAll('audio,video').forEach(m=>{try{m.pause();}catch{}});}},true);window.addEventListener('resize',()=>{if(document.getElementById('companyHubStoryViewerDialog')?.open)companyHubFitStoryText62();});}
  /* Assurance Regent v6.3.62 — slideshow statuses and algorithmic trending END */
