  /* Assurance Regent v6.3.60 — three-department paging and department-aware directory START */
  const COMPANY_HUB_DEPARTMENT_PAGE_SIZE60=3;
  let companyHubDepartmentPage60=0,companyHubDepartmentDirectoryBound60=false;
  function companyHubDepartmentNorm60(value=''){return String(value||'').trim().toLocaleLowerCase();}
  function companyHubDepartmentButtons60(){const nav=$('companyHubDepartments');if(!nav)return {nav:null,lounge:null,deps:[]};const buttons=[...nav.querySelectorAll('[data-company-hub-department]')],lounge=buttons.find(b=>companyHubDecodeDepartment53?.(b.dataset.companyHubDepartment)==='Company Lounge')||null,deps=buttons.filter(b=>b!==lounge);return {nav,lounge,deps};}
  function companyHubRenderDepartmentPagination60(){const {nav,lounge,deps}=companyHubDepartmentButtons60();if(!nav)return;const activeIndex=deps.findIndex(b=>b.classList.contains('active')),pages=Math.max(1,Math.ceil(deps.length/COMPANY_HUB_DEPARTMENT_PAGE_SIZE60));if(activeIndex>=0)companyHubDepartmentPage60=Math.floor(activeIndex/COMPANY_HUB_DEPARTMENT_PAGE_SIZE60);companyHubDepartmentPage60=Math.max(0,Math.min(companyHubDepartmentPage60,pages-1));const start=companyHubDepartmentPage60*COMPANY_HUB_DEPARTMENT_PAGE_SIZE60,end=start+COMPANY_HUB_DEPARTMENT_PAGE_SIZE60;if(lounge)lounge.hidden=false;deps.forEach((button,index)=>{button.hidden=index<start||index>=end;});nav.querySelector('#companyHubDepartmentPagination')?.remove();let pager=nav.querySelector('#companyHubDepartmentPagination60');if(!pager){pager=document.createElement('div');pager.id='companyHubDepartmentPagination60';pager.className='company-hub-department-pagination';nav.appendChild(pager);}pager.innerHTML=deps.length>COMPANY_HUB_DEPARTMENT_PAGE_SIZE60?`<button type="button" data-company-department-page60="prev" ${companyHubDepartmentPage60===0?'disabled':''} aria-label="Previous departments">‹ Prev</button><span>${companyHubDepartmentPage60+1} / ${pages}</span><button type="button" data-company-department-page60="next" ${companyHubDepartmentPage60>=pages-1?'disabled':''} aria-label="Next departments">Next ›</button>`:'';pager.hidden=deps.length<=COMPANY_HUB_DEPARTMENT_PAGE_SIZE60;}
  function companyHubDirectoryPeople60(){const all=companyFilteredEmployees(),dep=String(state.companyHubDepartment||'Company Lounge');if(dep==='Company Lounge')return all.slice(0,3);const target=companyHubDepartmentNorm60(dep);return all.filter(person=>companyHubDepartmentNorm60(person.department||'Unassigned')===target).slice(0,3);}
  function companyHubRenderDirectory60(){const host=$('companyHubPeople');if(!host)return;const dep=String(state.companyHubDepartment||'Company Lounge'),groups=companyHubStatusGroups(),rows=companyHubDirectoryPeople60();host.innerHTML=rows.map(p=>{const id=String(directoryPersonKey(p)||''),live=groups.has(id),photo=safeProfilePhoto(p.profilePhoto),name=String(p.name||p.id||'Colleague');return `<button type="button" class="social-person-row" data-company-person="${esc(id)}"><span class="company-social-avatar small ${live?'story-live':''}" ${live?`data-company-story-owner="${esc(id)}"`:''}>${photo?`<img src="${esc(photo)}" alt="${esc(name)}"/>`:esc(companyHubSocialLayerInitials(name))}</span><span><b>${esc(name)}</b><small>${esc(p.position||p.department||'Company member')}</small></span></button>`;}).join('')||`<div class="company-social-empty small">${dep==='Company Lounge'?'No company profiles here yet.':`No profiles are assigned to ${esc(dep)} yet.`}</div>`;host.insertAdjacentHTML('beforeend','<button type="button" class="company-hub-directory-more" data-company-hub-directory-more>More · Full directory</button>');}
  function renderCompanyHubDepartmentDirectory60(){if(!document.body.classList.contains('department-hub-social-mode'))return;companyHubRenderDepartmentPagination60();companyHubRenderDirectory60();}
  function bindCompanyHubDepartmentDirectory60(){if(companyHubDepartmentDirectoryBound60)return;companyHubDepartmentDirectoryBound60=true;document.addEventListener('click',e=>{const pager=e.target.closest('[data-company-department-page60]');if(pager){e.preventDefault();const {deps}=companyHubDepartmentButtons60(),pages=Math.max(1,Math.ceil(deps.length/COMPANY_HUB_DEPARTMENT_PAGE_SIZE60)),action=String(pager.dataset.companyDepartmentPage60||'');if(action==='prev')companyHubDepartmentPage60=Math.max(0,companyHubDepartmentPage60-1);if(action==='next')companyHubDepartmentPage60=Math.min(pages-1,companyHubDepartmentPage60+1);companyHubRenderDepartmentPagination60();return;}if(e.target.closest('[data-company-hub-department]'))setTimeout(renderCompanyHubDepartmentDirectory60,0);});renderCompanyHubDepartmentDirectory60();}
  /* Assurance Regent v6.3.60 — three-department paging and department-aware directory END */
