  /* Assurance Regent v6.3.113 — flag country picker and saved-country context START */
  const COMPANY_COUNTRY_FLAGS_SCHEMA113='6.3.113',COMPANY_COUNTRY_SAVED_EVENT113='assurance-regent-company-country-saved',COMPANY_COUNTRY_FLAG_BASE113='https://flagcdn.com/24x18/';
  let companyCountryMenu113=null,companyCountryMenuOwner113=null,companyCountryPickerSeq113=0;
  function countryCode113(value=''){const code=String(value||'').trim().toUpperCase();return /^[A-Z]{2}$/u.test(code)?code:'';}
  function countryRow113(value=''){const raw=String(value||'').trim(),code=countryCode113(raw),rows=companyProfileCountryRows111();return (code?rows.find(x=>countryCode113(x.countryCode)===code):null)||rows.find(x=>String(x.country||'').trim().toLowerCase()===raw.toLowerCase())||null;}
  function countryFlagUrl113(code=''){const normalized=countryCode113(code);return normalized?`${COMPANY_COUNTRY_FLAG_BASE113}${normalized.toLowerCase()}.png`:'';}
  function countryFlagVisual113(code='',name=''){
    const normalized=countryCode113(code),box=document.createElement('span');box.setAttribute('data-country-flag-visual113',normalized||'none');Object.assign(box.style,{width:'26px',height:'20px',display:'inline-flex',alignItems:'center',justifyContent:'center',flex:'0 0 26px',borderRadius:'4px',overflow:'hidden',background:'#f3f7f9',boxShadow:'inset 0 0 0 1px rgba(11,43,58,.10)'});
    if(!normalized)return box;
    const img=document.createElement('img'),fallback=document.createElement('span');img.src=countryFlagUrl113(normalized);img.alt='';img.width=24;img.height=18;img.loading='lazy';img.decoding='async';img.referrerPolicy='no-referrer';Object.assign(img.style,{display:'block',width:'24px',height:'18px',objectFit:'cover'});fallback.textContent=normalized;fallback.title=name||normalized;Object.assign(fallback.style,{display:'none',fontSize:'9px',fontWeight:'800',letterSpacing:'.04em',lineHeight:'1',color:'#33515f'});img.addEventListener('error',()=>{img.style.display='none';fallback.style.display='inline';},{once:true});box.append(img,fallback);return box;
  }
  function countryPickerRows113(){return companyProfileCountryRows111().filter(x=>countryCode113(x.countryCode)&&String(x.country||'').trim()).sort((a,b)=>String(a.country||'').localeCompare(String(b.country||'')));}
  function countryPickerSelectedRow113(select){return countryRow113(select?.value||'');}
  function countryPickerSync113(select){
    if(!select)return;const wrapper=select.nextElementSibling?.matches?.('[data-country-flag-picker113]')?select.nextElementSibling:select._countryFlagWrapper113,button=wrapper?.querySelector?.('[data-country-flag-trigger113]');if(!wrapper||!button)return;
    const row=countryPickerSelectedRow113(select),code=countryCode113(row?.countryCode||select.value||''),flag=button.querySelector('[data-country-flag-current113]'),text=button.querySelector('[data-country-flag-text113]');if(flag){flag.replaceChildren(countryFlagVisual113(code,row?.country||''));}if(text)text.textContent=row?.country||'Select registered country';button.dataset.countryCode113=code;button.title=row?`${row.country} (${code})`:'Select registered country';button.disabled=Boolean(select.disabled);button.setAttribute('aria-disabled',button.disabled?'true':'false');
  }
  function countryPickerClose113({restoreFocus=false}={}){
    const owner=companyCountryMenuOwner113;if(companyCountryMenu113){companyCountryMenu113.remove();companyCountryMenu113=null;}companyCountryMenuOwner113=null;if(owner?.button){owner.button.setAttribute('aria-expanded','false');if(restoreFocus&&!owner.button.disabled)owner.button.focus({preventScroll:true});}
  }
  function countryPickerPosition113(menu,button){
    if(!menu||!button)return;const rect=button.getBoundingClientRect(),gap=6,pad=12,availableWidth=Math.max(160,window.innerWidth-pad*2),width=Math.min(Math.max(rect.width,280),availableWidth),maxHeight=Math.min(390,Math.max(140,window.innerHeight-pad*2)),below=window.innerHeight-rect.bottom-pad,top=below>=Math.min(260,maxHeight)?rect.bottom+gap:Math.max(pad,rect.top-maxHeight-gap),left=Math.max(pad,Math.min(rect.left,window.innerWidth-width-pad));Object.assign(menu.style,{position:'fixed',left:`${Math.round(left)}px`,top:`${Math.round(top)}px`,width:`${Math.round(width)}px`,maxHeight:`${Math.round(maxHeight)}px`,zIndex:'2147483646'});
  }
  function countryPickerOpen113(select,button){
    if(!select||!button||button.disabled)return;countryPickerClose113();const rows=countryPickerRows113();if(rows.length<195)return toast('The registered-country catalogue is unavailable.');
    const menu=document.createElement('div'),searchWrap=document.createElement('div'),search=document.createElement('input'),list=document.createElement('div'),menuId=`countryFlagList113-${++companyCountryPickerSeq113}`;menu.setAttribute('data-country-flag-menu113','true');menu.setAttribute('aria-label','Registered country picker');Object.assign(menu.style,{background:'#fff',border:'1px solid #bdd1db',borderRadius:'14px',boxShadow:'0 18px 50px rgba(8,38,51,.24)',overflow:'hidden',display:'flex',flexDirection:'column'});searchWrap.style.padding='10px';searchWrap.style.borderBottom='1px solid #e1ebef';search.type='search';search.placeholder='Search country or code';search.autocomplete='off';search.spellcheck=false;search.setAttribute('aria-label','Search registered countries');Object.assign(search.style,{width:'100%',minHeight:'42px',boxSizing:'border-box',border:'1px solid #b9d0dc',borderRadius:'10px',padding:'0 12px',font:'inherit',color:'#0b2b3a',background:'#fff',outline:'none'});list.id=menuId;list.setAttribute('role','listbox');list.setAttribute('aria-label','Registered countries');Object.assign(list.style,{overflowY:'auto',overscrollBehavior:'contain',padding:'6px',minHeight:'0',maxHeight:'320px',flex:'1 1 auto'});searchWrap.appendChild(search);menu.append(searchWrap,list);document.body.appendChild(menu);companyCountryMenu113=menu;companyCountryMenuOwner113={select,button};button.setAttribute('aria-expanded','true');button.setAttribute('aria-controls',menuId);countryPickerPosition113(menu,button);
    const selected=countryCode113(select.value);let visibleOptions=[];
    const render=(query='')=>{const q=String(query||'').trim().toLowerCase();list.replaceChildren();visibleOptions=[];for(const row of rows){const code=countryCode113(row.countryCode),name=String(row.country||'').trim();if(q&&!name.toLowerCase().includes(q)&&!code.toLowerCase().includes(q))continue;const option=document.createElement('button'),label=document.createElement('span'),codeEl=document.createElement('span');option.type='button';option.setAttribute('role','option');option.setAttribute('aria-selected',code===countryCode113(select.value)?'true':'false');option.dataset.countryOption113=code;Object.assign(option.style,{width:'100%',minHeight:'42px',border:'0',borderRadius:'9px',background:code===countryCode113(select.value)?'#edf8fb':'transparent',display:'flex',alignItems:'center',gap:'10px',padding:'7px 10px',font:'inherit',textAlign:'left',cursor:'pointer',color:'#0b2b3a'});label.textContent=name;Object.assign(label.style,{flex:'1 1 auto',minWidth:'0',fontWeight:code===countryCode113(select.value)?'700':'500'});codeEl.textContent=code;Object.assign(codeEl.style,{flex:'0 0 auto',fontSize:'11px',fontWeight:'800',letterSpacing:'.04em',color:'#6a8490'});option.append(countryFlagVisual113(code,name),label,codeEl);option.addEventListener('mouseenter',()=>{option.style.background='#f1f8fa';});option.addEventListener('mouseleave',()=>{option.style.background=code===countryCode113(select.value)?'#edf8fb':'transparent';});option.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();select.value=code;select.dispatchEvent(new Event('input',{bubbles:true}));select.dispatchEvent(new Event('change',{bubbles:true}));countryPickerSync113(select);countryPickerClose113({restoreFocus:true});});option.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();countryPickerClose113({restoreFocus:true});return;}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const index=visibleOptions.indexOf(option),next=e.key==='ArrowDown'?Math.min(visibleOptions.length-1,index+1):Math.max(0,index-1);visibleOptions[next]?.focus();}});visibleOptions.push(option);list.appendChild(option);}if(!visibleOptions.length){const empty=document.createElement('div');empty.textContent='No countries match your search.';Object.assign(empty.style,{padding:'14px 12px',fontSize:'13px',color:'#6a8490'});list.appendChild(empty);}};
    render();search.addEventListener('input',()=>render(search.value));search.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();countryPickerClose113({restoreFocus:true});}else if(e.key==='ArrowDown'){e.preventDefault();visibleOptions[0]?.focus();}});requestAnimationFrame(()=>{search.focus({preventScroll:true});if(selected){const active=list.querySelector(`[data-country-option113="${CSS.escape(selected)}"]`);active?.scrollIntoView?.({block:'nearest'});}});
  }
  function countryFlagEnhanceSelect113(select,{surface='company-profile'}={}){
    if(!select||select.tagName!=='SELECT')return false;let wrapper=select.nextElementSibling?.matches?.('[data-country-flag-picker113]')?select.nextElementSibling:select._countryFlagWrapper113;if(!wrapper||!wrapper.isConnected){wrapper=document.createElement('div');wrapper.setAttribute('data-country-flag-picker113',surface);Object.assign(wrapper.style,{position:'relative',width:'100%',minWidth:'0'});const button=document.createElement('button'),current=document.createElement('span'),flag=document.createElement('span'),text=document.createElement('span'),chevron=document.createElement('span');button.type='button';button.setAttribute('role','combobox');button.setAttribute('aria-haspopup','listbox');button.setAttribute('aria-expanded','false');button.setAttribute('data-country-flag-trigger113','true');button.setAttribute('aria-label','Registered country');Object.assign(button.style,{width:'100%',minHeight:'48px',boxSizing:'border-box',border:'1px solid #b9d0dc',borderRadius:'13px',background:'#fff',padding:'0 13px',display:'flex',alignItems:'center',justifyContent:'space-between',gap:'10px',font:'inherit',color:'#0b2b3a',textAlign:'left',cursor:'pointer'});current.setAttribute('data-country-flag-selection113','true');Object.assign(current.style,{display:'inline-flex',alignItems:'center',gap:'10px',minWidth:'0',flex:'1 1 auto'});flag.setAttribute('data-country-flag-current113','true');text.setAttribute('data-country-flag-text113','true');Object.assign(text.style,{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap',fontWeight:'600'});chevron.textContent='▾';chevron.setAttribute('aria-hidden','true');Object.assign(chevron.style,{fontSize:'12px',color:'#55727e',flex:'0 0 auto'});current.append(flag,text);button.append(current,chevron);wrapper.appendChild(button);select.insertAdjacentElement('afterend',wrapper);select._countryFlagWrapper113=wrapper;button.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(companyCountryMenuOwner113?.button===button)countryPickerClose113();else countryPickerOpen113(select,button);});button.addEventListener('keydown',e=>{if(['Enter',' ','ArrowDown'].includes(e.key)){e.preventDefault();countryPickerOpen113(select,button);}else if(e.key==='Escape')countryPickerClose113();});if(!select.dataset.countryFlagListener113){select.dataset.countryFlagListener113='true';select.addEventListener('change',()=>countryPickerSync113(select));}}
    select.dataset.countryFlagEnhanced113='true';select.dataset.countryFlagSurface113=surface;Object.assign(select.style,{position:'absolute',width:'1px',height:'1px',padding:'0',margin:'0',border:'0',opacity:'0',pointerEvents:'none',overflow:'hidden',clip:'rect(0 0 0 0)',clipPath:'inset(50%)',whiteSpace:'nowrap'});select.tabIndex=-1;select.setAttribute('aria-hidden','true');countryPickerSync113(select);return true;
  }
  function companyCountryDispatch113(detail={}){const payload={schema:COMPANY_COUNTRY_FLAGS_SCHEMA113,persisted:true,...detail};window.dispatchEvent(new CustomEvent(COMPANY_COUNTRY_SAVED_EVENT113,{detail:payload}));return payload;}
  async function companyCountryAfterPersist113({companyId='',beforeCode='',expectedCode='',source='company-profile'}={}){
    const id=String(companyId||''),company=(typeof companyProfileById67==='function'?companyProfileById67(id):null)||(typeof companyMasterRow110==='function'?companyMasterRow110(id):null)||(typeof companyById==='function'?companyById(id):null)||{},code=countryCode113(company.registeredCountryCode||company.countryCode||expectedCode),row=countryRow113(code||company.registeredCountry||''),countryName=String(company.registeredCountry||row?.country||'').trim(),previous=countryCode113(beforeCode),changed=Boolean(code&&previous!==code);let calendarRefreshed=false,calendarReady=true;
    const holidayApi=window.AssuranceRegentCompanyHolidays,activeContext=holidayApi?.context?.()||{},isActive=!id||String(activeContext.companyId||'')===id||String(typeof currentCompanyId==='function'?currentCompanyId():'')===id;
    if(changed&&isActive){const synced=state.companyHolidayContext109||{},alreadySynced=countryCode113(synced.countryCode)===code&&String(synced.companyId||'')===id;calendarRefreshed=alreadySynced;if(!alreadySynced&&holidayApi?.refresh){companyHolidayCache109?.clear?.();state.companyHolidayContext109=null;try{await holidayApi.refresh();calendarRefreshed=true;}catch{calendarReady=false;}}else if(!alreadySynced&&!holidayApi?.refresh)calendarReady=false;}
    const syncedAfter=state.companyHolidayContext109||{};if(changed&&isActive&&countryCode113(syncedAfter.countryCode)!==code)calendarReady=false;
    return companyCountryDispatch113({companyId:id,countryCode:code,countryName,previousCountryCode:previous,changed,source,calendarHolidayRefreshOnCountryChange:true,calendarRefreshed,calendarReady});
  }
  const companyProfileCountrySelectBefore113=companyProfileCountrySelect112;
  companyProfileCountrySelect112=function(){const ok=companyProfileCountrySelectBefore113();if(ok)countryFlagEnhanceSelect113($('companyProfileCountry67'),{surface:'company-profile'});return ok;};
  if(typeof enhanceDeveloperCompanyCards110==='function'){const enhanceDeveloperCompanyCardsBefore113=enhanceDeveloperCompanyCards110;enhanceDeveloperCompanyCards110=function(){const value=enhanceDeveloperCompanyCardsBefore113();document.querySelectorAll('#developerCompanyDirectory select[data-company-registered-country]').forEach(select=>countryFlagEnhanceSelect113(select,{surface:'company-master'}));return value;};}
  const saveCompanyProfileEditBefore113=saveCompanyProfileEdit67;
  saveCompanyProfileEdit67=async function(){
    if(!companyProfileDeveloper111())return saveCompanyProfileEditBefore113();const companyId=String(companyProfileEditTarget67||''),before=companyProfileById67(companyId)||{},beforeCode=countryCode113(before.registeredCountryCode||''),expectedCode=countryCode113($('companyProfileCountry67')?.value||'');const result=await saveCompanyProfileEditBefore113();const after=companyProfileById67(companyId)||{},savedCode=countryCode113(after.registeredCountryCode||'');if(companyId&&expectedCode&&savedCode===expectedCode&&String(companyProfileEditTarget67||'')==='')await companyCountryAfterPersist113({companyId,beforeCode,expectedCode,source:'company-profile'});return result;
  };
  if(typeof saveCompanyMaster110==='function'){const saveCompanyMasterBefore113=saveCompanyMaster110;saveCompanyMaster110=async function(id){const companyId=String(id||''),before=companyMasterRow110(companyId)||{},beforeCode=countryCode113(before.registeredCountryCode||''),card=document.querySelector(`#developerCompanyDirectory [data-company-card="${CSS.escape(companyId)}"]`),expectedCode=countryCode113(card?.querySelector('[data-company-registered-country]')?.value||'');const result=await saveCompanyMasterBefore113(companyId);if(result===true&&companyId&&expectedCode){const after=companyMasterRow110(companyId)||{},savedCode=countryCode113(after.registeredCountryCode||'');if(savedCode===expectedCode)await companyCountryAfterPersist113({companyId,beforeCode,expectedCode,source:'company-master'});}return result;};}
  document.addEventListener('pointerdown',e=>{if(!companyCountryMenu113)return;const target=e.target;if(companyCountryMenu113.contains(target)||companyCountryMenuOwner113?.button?.contains(target))return;countryPickerClose113();},true);
  window.addEventListener('resize',()=>countryPickerClose113());window.addEventListener('scroll',e=>{if(companyCountryMenu113&&(e.target===companyCountryMenu113||companyCountryMenu113.contains?.(e.target)))return;countryPickerClose113();},true);
  window.AssuranceRegentCompanyCountryContext={schema:COMPANY_COUNTRY_FLAGS_SCHEMA113,event:COMPANY_COUNTRY_SAVED_EVENT113,flagSource:'flagcdn.com',flagImages:true,flagFallback:'ISO-2',searchable:true,minimumCountries:195,nativeSelectAuthoritative:true,persistedFields:['registeredCountry','registeredCountryCode'],calendarHolidayRefreshOnCountryChange:true,refreshControls:()=>{companyProfileCountrySelect112();document.querySelectorAll('#developerCompanyDirectory select[data-company-registered-country]').forEach(select=>countryFlagEnhanceSelect113(select,{surface:'company-master'}));}};
  queueMicrotask(()=>{try{if($('companyProfileCountry67'))companyProfileCountrySelect112();if(typeof enhanceDeveloperCompanyCards110==='function')enhanceDeveloperCompanyCards110();}catch{}});
  /* Assurance Regent v6.3.113 — flag country picker and saved-country context END */
