  /* Assurance Regent v6.3.111 — Developer full company profile edit START */
  const COMPANY_PROFILE_DEVELOPER_UNLOCK_SCHEMA111='6.3.111';
  function companyProfileDeveloper111(){return companyProfileAuthority67?.()==='DEVELOPER'||controlUser()?.role==='Developer';}
  function companyProfileCountryRows111(){const map=new Map();for(const row of (window.ADRA_CURRENCIES||[])){const code=String(row?.countryCode||'').trim().toUpperCase(),name=String(row?.country||'').trim();if(code&&name&&!map.has(code))map.set(code,{countryCode:code,country:name});}return [...map.values()].sort((a,b)=>a.country.localeCompare(b.country));}
  function companyProfileCountry111(value=''){const raw=String(value||'').trim(),rows=companyProfileCountryRows111();if(!raw)return null;const upper=raw.toUpperCase();return rows.find(x=>x.countryCode===upper)||rows.find(x=>x.country.toLowerCase()===raw.toLowerCase())||null;}
  function unlockDeveloperCompanyProfile111(){
    const dialog=$('companyProfileEditDialog67');if(!dialog||!companyProfileDeveloper111())return false;
    const editable=['companyProfileName67','companyProfileCode67','companyProfileEmail67','companyProfilePhone67','companyProfileCountry67','companyProfileMeet67'];for(const id of editable){const el=$(id);if(!el)continue;el.disabled=false;el.readOnly=false;el.removeAttribute('readonly');el.removeAttribute('aria-readonly');}
    const code=$('companyProfileCode67');if(code){code.maxLength=24;code.autocomplete='off';}
    const country=$('companyProfileCountry67');if(country){if(country.value==='Not set')country.value='';let list=$('companyProfileCountryList111');if(!list){list=document.createElement('datalist');list.id='companyProfileCountryList111';document.body.appendChild(list);}list.innerHTML=companyProfileCountryRows111().map(x=>`<option value="${esc(x.country)}">${esc(x.countryCode)}</option>`).join('');country.setAttribute('list',list.id);country.placeholder='Select or type registered country';}
    const meet=$('companyProfileMeet67');if(meet){if(meet.value==='Not set')meet.value='';meet.placeholder='https://meet.google.com/abc-defg-hij';}
    const logo=$('companyProfileLogo67');if(logo)logo.disabled=false;
    const head=dialog.querySelector('.company-profile-edit-head67 p');if(head)head.textContent='Complete or correct the organization information shown across Assurance Regent. Developer authority can edit every company profile field shown here.';
    const boundary=dialog.querySelector('.company-profile-boundary67');if(boundary)boundary.innerHTML='<b>Developer edit access</b><span>All company profile fields shown above are editable. Only the internal company ID remains fixed so linked operational records keep their stable company key.</span>';
    dialog.dataset.developerProfileUnlocked111='true';return true;
  }
  const openCompanyProfileEditBefore111=openCompanyProfileEdit67;
  openCompanyProfileEdit67=function(companyId=''){openCompanyProfileEditBefore111(companyId);if(companyProfileDeveloper111())queueMicrotask(unlockDeveloperCompanyProfile111);};
  const saveCompanyProfileEditBefore111=saveCompanyProfileEdit67;
  saveCompanyProfileEdit67=async function(){
    if(!companyProfileDeveloper111())return saveCompanyProfileEditBefore111();
    if(companyProfileEditBusy67)return;const company=companyProfileById67(companyProfileEditTarget67);if(!company)return toast('Company profile was not found.');
    const name=$('companyProfileName67')?.value.trim()||'',code=$('companyProfileCode67')?.value.trim().toUpperCase()||'',email=$('companyProfileEmail67')?.value.trim().toLowerCase()||'',phone=$('companyProfilePhone67')?.value.trim()||'',countryInput=$('companyProfileCountry67')?.value.trim()||'',country=companyProfileCountry111(countryInput),meetRaw=$('companyProfileMeet67')?.value.trim()||'',meet=meetRaw?normalizeGoogleMeetUrl(meetRaw):'',logoFile=$('companyProfileLogo67')?.files?.[0]||null;
    if(!name)return toast('Company name is required.');if(!/^[A-Z0-9][A-Z0-9_-]{1,23}$/u.test(code))return toast('Company code must contain 2 to 24 letters, numbers, hyphens or underscores.');if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/u.test(email))return toast('Enter a valid company email address.');if(phone.length>40)return toast('Contact number is too long.');if(!country)return toast('Choose a valid registered country from the country list.');if(meetRaw&&!meet)return toast('Enter a valid Google Meet interview room.');if(logoFile&&!String(logoFile.type||'').toLowerCase().startsWith('image/'))return toast('Choose an image file for the company logo.');
    const countryChanged=String(company.registeredCountryCode||'').toUpperCase()!==country.countryCode;const save=$('companyProfileEditDialog67')?.querySelector('[data-company-profile-save67]');companyProfileEditBusy67=true;if(save){save.disabled=true;save.textContent='Saving…';}
    try{
      let logoFileId=null;if(logoFile){const stored=await uploadPersistentFile(logoFile,{category:'company-logo',companyId:company.id,entityType:'company',entityId:company.id,metadata:{companyName:name,updatedBy:controlActorId()}});logoFileId=stored?.fileId||null;}
      await supabaseRpc('assurance_regent_browser_admin_company_profile_update_v111',{p_token:browserSessionToken,p_company_id:company.id,p_name:name,p_code:code,p_email:email,p_phone:phone,p_country:country.country,p_country_code:country.countryCode,p_meet_url:meet,p_logo_file_id:logoFileId},{bypassCache:true});
      if(countryChanged){companyHolidayCache109?.clear?.();state.companyHolidayContext109=null;}await loadStandaloneState();await refreshControlCenter();companyProfileEditBusy67=false;const dialog=$('companyProfileEditDialog67');if(dialog?.open)dialog.close();resetCompanyProfileLogoPreview67();companyProfileEditTarget67='';renderCompany();if(typeof renderSettingsPane==='function')renderSettingsPane();if(countryChanged){try{await window.AssuranceRegentCompanyHolidays?.refresh?.();}catch{}}toast(countryChanged?'Company profile updated. Registered country changed and the holiday calendar is refreshing.':'Company profile updated.');
    }catch(err){companyProfileEditBusy67=false;if(save){save.disabled=false;save.textContent='Save changes';}unlockDeveloperCompanyProfile111();toast(err?.message||String(err));}
  };
  window.AssuranceRegentDeveloperCompanyProfile={schema:COMPANY_PROFILE_DEVELOPER_UNLOCK_SCHEMA111,developerOnly:true,visibleFieldsEditable:['logo','name','code','email','phone','registeredCountry','interviewMeetUrl'],immutable:['companyId'],countryChangeRefreshesHolidays:true};
  /* Assurance Regent v6.3.111 — Developer full company profile edit END */
