  /* Assurance Regent v6.3.110 — Developer company master edit START */
  const COMPANY_MASTER_EDIT_SCHEMA110='6.3.110';
  const companyMasterEditMode110=new Set();
  function companyMasterRow110(id=''){return companyById?.(id)||((state.control?.profile?.companies||[]).find(x=>String(x.id)===String(id)))||null;}
  function companyMasterCurrency110(company={}){return String(company.operatingCurrency||company.currency||company.billingCurrency||state.control?.settings?.currency||'USD').trim().toUpperCase()||'USD';}
  function enhanceDeveloperCompanyCards110(){
    if(controlUser()?.role!=='Developer')return;
    for(const card of document.querySelectorAll('#developerCompanyDirectory [data-company-card]')){
      const id=String(card.dataset.companyCard||''),company=companyMasterRow110(id);if(!id||!company)continue;const editing=companyMasterEditMode110.has(id),grid=card.querySelector('.company-billing-grid'),actions=card.querySelector('.company-service-actions');if(!grid||!actions)continue;
      if(!card.querySelector('[data-company-name]'))grid.insertAdjacentHTML('afterbegin',`<label>Company name<input data-company-name data-company-master-field value="${esc(company.name||'')}" /></label><label>Company code<input data-company-code data-company-master-field maxlength="24" value="${esc(company.code||'')}" /></label><label>Operating currency<input data-company-operating-currency data-company-master-field maxlength="8" value="${esc(companyMasterCurrency110(company))}" /><small>Used by company financial and holiday context where applicable.</small></label>`);
      const country=card.querySelector('[data-company-registered-country]');if(country){country.removeAttribute('title');country.innerHTML=companyCountryOptions(company.registeredCountryCode||'');const help=country.parentElement?.querySelector('small');if(help)help.textContent='Developer editable · changing this refreshes the company public-holiday calendar.';}
      for(const el of card.querySelectorAll('[data-company-name],[data-company-code],[data-company-operating-currency],[data-company-registered-country],[data-company-amount],[data-company-currency],[data-company-payment],[data-company-message],[data-company-meet-url]'))el.disabled=!editing;
      const legacySave=card.querySelector('[data-company-save]');if(legacySave)legacySave.hidden=editing;
      let controls=actions.querySelector('.company-master-edit-actions110');if(!controls){controls=document.createElement('div');controls.className='company-master-edit-actions110';controls.innerHTML=`<button type="button" class="btn small ghost" data-company-master-edit="${encodeURIComponent(id)}">Edit company</button><button type="button" class="btn small primary" data-company-master-save="${encodeURIComponent(id)}" hidden>Save changes</button><button type="button" class="btn small ghost" data-company-master-cancel="${encodeURIComponent(id)}" hidden>Cancel</button>`;actions.appendChild(controls);}controls.querySelector('[data-company-master-edit]').hidden=editing;controls.querySelector('[data-company-master-save]').hidden=!editing;controls.querySelector('[data-company-master-cancel]').hidden=!editing;
    }
  }
  function companyMasterPayload110(card,id){const countryCode=card.querySelector('[data-company-registered-country]')?.value||'',country=countryByCode(countryCode);return {id,name:card.querySelector('[data-company-name]')?.value.trim()||'',code:card.querySelector('[data-company-code]')?.value.trim().toUpperCase()||'',countryCode,countryName:String(country?.country||'').trim(),operatingCurrency:card.querySelector('[data-company-operating-currency]')?.value.trim().toUpperCase()||'',billingCurrency:card.querySelector('[data-company-currency]')?.value.trim().toUpperCase()||'',monthlyAmount:Number(card.querySelector('[data-company-amount]')?.value||0),paymentAccount:card.querySelector('[data-company-payment]')?.value.trim()||'',billingMessage:card.querySelector('[data-company-message]')?.value.trim()||'',meetUrl:normalizeGoogleMeetUrl(card.querySelector('[data-company-meet-url]')?.value||''),enabled:Boolean(card.querySelector('[data-company-enabled]')?.checked)};}
  async function saveCompanyMaster110(id){
    if(controlUser()?.role!=='Developer')return toast('Developer permission is required.');const card=document.querySelector(`#developerCompanyDirectory [data-company-card="${CSS.escape(id)}"]`),before=companyMasterRow110(id);if(!card||!before)return toast('Company could not be found.');const p=companyMasterPayload110(card,id);if(!p.name||!p.code||!p.countryName||!p.countryCode||!p.operatingCurrency||!p.billingCurrency||!p.meetUrl)return toast('Company name, code, registered country, operating currency, billing currency and Google Meet room are required.');if(p.monthlyAmount<0)return toast('Monthly amount cannot be negative.');const countryChanged=String(before.registeredCountryCode||'').toUpperCase()!==p.countryCode;if(countryChanged&&!confirm(`Change registered country from ${before.registeredCountry||before.registeredCountryCode||'the current country'} to ${p.countryName}? The company holiday calendar will be rebuilt for the new country.`))return;
    try{await supabaseRpc('assurance_regent_browser_admin_company_master_update',{p_token:browserSessionToken,p_company_id:id,p_name:p.name,p_code:p.code,p_country:p.countryName,p_country_code:p.countryCode,p_operating_currency:p.operatingCurrency,p_billing_currency:p.billingCurrency,p_monthly_amount:p.monthlyAmount,p_payment_account:p.paymentAccount,p_billing_message:p.billingMessage,p_meet_url:p.meetUrl,p_enabled:p.enabled},{bypassCache:true});companyMasterEditMode110.delete(id);if(countryChanged){companyHolidayCache109?.clear?.();state.companyHolidayContext109=null;}await loadStandaloneState();await refreshControlCenter();renderSettingsPane();if(countryChanged){try{await window.AssuranceRegentCompanyHolidays?.refresh?.();}catch{}}toast(countryChanged?'Company updated. Registered country changed and the holiday calendar is refreshing.':'Company master details updated.');return true;}catch(err){toast(err.message||'Could not update company details.');return false;}
  }
  const renderSettingsPaneBeforeCompanyMaster110=renderSettingsPane;
  renderSettingsPane=function(){renderSettingsPaneBeforeCompanyMaster110();enhanceDeveloperCompanyCards110();};
  const syncCompanyHolidaysBeforeMaster110=syncCompanyHolidays109;
  syncCompanyHolidays109=async function(force=false){const ctx=companyHolidayContext109(),country=String(ctx.countryName||ctx.countryCode||'').trim(),companyId=String(ctx.companyId||'');let cleaned=false;if(country&&companyId&&engine?.state?.calendar){const before=engine.state.calendar.length;engine.state.calendar=engine.state.calendar.filter(x=>{const src=String(x.holidaySource||'');if(String(x.companyId||'')!==companyId||!src.startsWith('Official public holiday · ')||!src.endsWith(' · Nager.Date'))return true;return src.includes(` · ${country} · Nager.Date`);});cleaned=engine.state.calendar.length!==before;if(cleaned)persistLocalLiveState();}const changed=await syncCompanyHolidaysBeforeMaster110(force);return cleaned||changed;};
  document.addEventListener('click',e=>{const edit=e.target.closest?.('[data-company-master-edit]'),save=e.target.closest?.('[data-company-master-save]'),cancel=e.target.closest?.('[data-company-master-cancel]');if(edit){const id=decodeURIComponent(edit.dataset.companyMasterEdit||'');companyMasterEditMode110.add(id);enhanceDeveloperCompanyCards110();return;}if(cancel){const id=decodeURIComponent(cancel.dataset.companyMasterCancel||'');companyMasterEditMode110.delete(id);renderSettingsPane();return;}if(save){const id=decodeURIComponent(save.dataset.companyMasterSave||'');saveCompanyMaster110(id);}});
  window.AssuranceRegentCompanyMasterEdit={schema:COMPANY_MASTER_EDIT_SCHEMA110,developerOnly:true,editable:['name','code','registeredCountry','operatingCurrency','billingCurrency','monthlyAmount','paymentAccount','billingMessage','interviewMeetUrl'],immutable:['companyId'],countryChangeRefreshesHolidays:true};
  /* Assurance Regent v6.3.110 — Developer company master edit END */
