  /* Assurance Regent v6.3.78 — Google Meet Jivan interview assistant START */
  const MEET_READ_SCOPE78='https://www.googleapis.com/auth/meetings.space.readonly';
  let meetAssistantStatus78=null,meetAssistantBusy78=false;
  function meetInterviewRequest78(payload={}){return baseSupabaseFunction77('meet-interview-assistant',payload);}
  async function loadMeetAssistantStatus78(force=false){if(!browserSessionToken)return {connected:false,meet_scope:false};if(meetAssistantStatus78&&!force)return meetAssistantStatus78;try{meetAssistantStatus78=await meetInterviewRequest78({action:'status'});return meetAssistantStatus78;}catch(err){meetAssistantStatus78={connected:false,meet_scope:false,error:err?.message||String(err)};return meetAssistantStatus78;}}
  function meetWaitForScope78(popup,timeoutMs=180000){
    return new Promise((resolve,reject)=>{let done=false,timer=null,poll=null;const finish=(fn,value)=>{if(done)return;done=true;clearTimeout(timer);clearInterval(poll);window.removeEventListener('message',onMessage);try{if(popup&&!popup.closed)popup.close();}catch{}fn(value);};const check=async()=>{try{const x=await loadMeetAssistantStatus78(true);if(x?.meet_scope)return finish(resolve,x);if(popup?.closed)return finish(reject,new Error('Google authorization closed before Meet transcript access was granted.'));}catch{}};const onMessage=e=>{if(e.origin!==location.origin)return;const data=e.data||{};if(data.type==='assurance-regent-gmail-connected')setTimeout(check,120);else if(data.type==='assurance-regent-gmail-error')finish(reject,new Error(data.message||'Google authorization was not completed.'));};window.addEventListener('message',onMessage);timer=setTimeout(()=>finish(reject,new Error('Google Meet authorization timed out. Try Connect Meet access again.')),timeoutMs);poll=setInterval(check,1800);});
  }
  async function authorizeMeetScope78(){
    const popup=gmailPopup77();if(!popup)throw new Error('Allow pop-ups for Assurance Regent so Google Workspace can be connected.');
    const auth=await gmailConnectorRequest77({action:'authorize_url'});if(!auth?.url)throw new Error('Google authorization URL could not be prepared.');
    popup.location.href=auth.url;try{popup.focus();}catch{}
    const x=await meetWaitForScope78(popup);
    await loadGmailStatus77(true);meetAssistantStatus78=x;
    renderMeetInterviewAssistant78();toast('Google Meet transcript access connected for Jivan interview notes.');return x;
  }
  async function ensureMeetScope78(){const x=await loadMeetAssistantStatus78(true);if(x?.meet_scope)return x;return authorizeMeetScope78();}
  function ensureMeetAssistantStyles78(){if($('meetInterviewAssistantStyles78'))return;const s=document.createElement('style');s.id='meetInterviewAssistantStyles78';s.textContent=`.meet-assistant78{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:12px 14px;margin:0 0 12px;border:1px solid #d8e8ef;border-radius:14px;background:#f8fcfd}.meet-assistant78-copy{display:flex;align-items:center;gap:10px;min-width:0}.meet-assistant78-mark{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:#eaf7fb;color:#075b78;font-weight:900}.meet-assistant78-copy div{display:grid;gap:2px}.meet-assistant78-copy b{font-size:12px}.meet-assistant78-copy small{font-size:10px;color:#647b87}.meet-assistant78-actions{display:flex;gap:7px;flex-wrap:wrap}.meet-note78-dialog{width:min(880px,94vw);max-height:88vh;border:0;border-radius:20px;padding:0;box-shadow:0 24px 80px #0d2d3b33}.meet-note78-dialog::backdrop{background:#08202b80}.meet-note78-head{display:flex;justify-content:space-between;gap:12px;padding:18px 20px;border-bottom:1px solid #e4edf1}.meet-note78-body{padding:18px 20px;overflow:auto;max-height:68vh;display:grid;gap:14px}.meet-note78-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.meet-note78-card{border:1px solid #e0eaee;border-radius:14px;padding:12px;background:#fbfdfe}.meet-note78-card h4{margin:0 0 7px;font-size:12px}.meet-note78-card p,.meet-note78-card li{font-size:11px;line-height:1.5;color:#324d5b}.meet-note78-card ul{margin:5px 0 0;padding-left:18px}.meet-note78-criterion{display:grid;grid-template-columns:140px 90px 1fr;gap:8px;padding:8px 0;border-bottom:1px solid #eef3f5;font-size:10px}.meet-note78-criterion:last-child{border-bottom:0}.meet-note78-status{font-weight:800}.meet-note78-warning{padding:10px 12px;border-radius:12px;background:#fff8e8;color:#765b18;font-size:10px}.meet-compare78-list{display:grid;gap:10px}.meet-compare78-person{border:1px solid #e0eaee;border-radius:14px;padding:12px;background:#fff}.meet-compare78-person h4{margin:0 0 8px;font-size:12px}.meet-compare78-person small{font-size:10px;color:#607885}.recruit-row-actions [data-jivan-interview-notes78]{white-space:nowrap}@media(max-width:720px){.meet-assistant78{align-items:flex-start;flex-direction:column}.meet-note78-grid{grid-template-columns:1fr}.meet-note78-criterion{grid-template-columns:1fr}.meet-assistant78-actions{width:100%}}`;document.head.appendChild(s);}
  function interviewAssistantHost78(){const table=$('recruitInterviewsTable');if(!table)return null;let host=$('meetInterviewAssistant78');if(!host){host=document.createElement('div');host.id='meetInterviewAssistant78';table.before(host);}return host;}
  async function renderMeetInterviewAssistant78(){ensureMeetAssistantStyles78();const host=interviewAssistantHost78();if(!host||!recruitmentHrAllowed())return;const x=await loadMeetAssistantStatus78(false),selected=String(state.recruitVacancy||'');host.className='meet-assistant78';host.innerHTML=`<div class="meet-assistant78-copy"><span class="meet-assistant78-mark">J</span><div><b>Jivan interview notes</b><small>${x?.meet_scope?`Google Meet transcript access connected${x.email?` · ${esc(x.email)}`:''}.`:'Connect Google Workspace so Jivan can read authorized Meet transcripts after interviews.'}</small></div></div><div class="meet-assistant78-actions">${x?.meet_scope?'':'<button type="button" class="btn micro primary" data-meet-connect78>Connect Meet access</button>'}<button type="button" class="btn micro ghost" data-meet-compare78 ${selected?'':'disabled title="Select one vacancy first"'}>Compare interview evidence</button></div>`;
    document.querySelectorAll('#recruitInterviewsTable [data-interview-action="room"]').forEach(room=>{const cell=room.closest('.recruit-row-actions');if(!cell||cell.querySelector('[data-jivan-interview-notes78]'))return;const id=room.dataset.interviewId||'';const b=document.createElement('button');b.type='button';b.className='btn micro secondary';b.dataset.jivanInterviewNotes78=id;b.textContent='Jivan notes';room.insertAdjacentElement('afterend',b);});
  }
  function ensureMeetNoteDialog78(){let d=$('meetInterviewNoteDialog78');if(d)return d;d=document.createElement('dialog');d.id='meetInterviewNoteDialog78';d.className='meet-note78-dialog';d.innerHTML='<div class="meet-note78-head"><div><small>JIVAN · INTERVIEW EVIDENCE</small><h3 id="meetInterviewNoteTitle78">Interview notes</h3></div><button type="button" class="btn micro ghost" data-meet-note-close78>Close</button></div><div class="meet-note78-body" id="meetInterviewNoteBody78"></div>';document.body.appendChild(d);return d;}
  function listMarkup78(rows=[]){return rows?.length?`<ul>${rows.map(x=>`<li>${esc(String(x||''))}</li>`).join('')}</ul>`:'<p>No evidence recorded.</p>';}
  function showInterviewNote78(note){const d=ensureMeetNoteDialog78(),a=note?.analysis||{};$('meetInterviewNoteTitle78').textContent=`${note?.candidate_name||a.candidate||'Candidate'} · Interview evidence`;$('meetInterviewNoteBody78').innerHTML=`<div class="meet-note78-warning">Advisory evidence only. Jivan does not rank, select, reject, or hire candidates. HR and the interview panel remain responsible for the employment decision.</div><div class="meet-note78-card"><h4>Interview summary</h4><p>${esc(a.summary||'No summary available.')}</p></div><div class="meet-note78-grid"><div class="meet-note78-card"><h4>Job-related strengths evidenced</h4>${listMarkup78(a.strengths)}</div><div class="meet-note78-card"><h4>Gaps / evidence not established</h4>${listMarkup78(a.gaps)}</div></div><div class="meet-note78-card"><h4>Vacancy criteria evidence</h4>${(a.criteria||[]).map(x=>`<div class="meet-note78-criterion"><b>${esc(x.criterion||'Criterion')}</b><span class="meet-note78-status">${esc(x.status||'NOT_EVIDENCED')}</span><span>${esc(x.evidence||'')}</span></div>`).join('')||'<p>No criteria evidence available.</p>'}</div><div class="meet-note78-card"><h4>Question-by-question notes</h4>${(a.question_notes||[]).map(x=>`<div class="meet-note78-criterion"><b>${esc(x.question||'Question')}</b><span>${esc(x.response_summary||'')}</span><span>${esc(x.evidence||'')}</span></div>`).join('')||'<p>No structured question notes available.</p>'}</div><div class="meet-note78-grid"><div class="meet-note78-card"><h4>Panel follow-up questions</h4>${listMarkup78(a.follow_up_questions)}</div><div class="meet-note78-card"><h4>Panel note</h4><p>${esc(a.panel_notes||'No additional panel note.')}</p></div></div><div class="meet-note78-card"><h4>Source</h4><p>${esc(note?.conference_record||'Google Meet conference')} · ${Number(note?.participant_count||0)} participant${Number(note?.participant_count||0)===1?'':'s'} · generated ${esc(note?.updated_at?new Date(note.updated_at).toLocaleString():'now')}</p></div>`;d.showModal();}
  async function analyzeInterview78(id){if(meetAssistantBusy78)return;meetAssistantBusy78=true;try{await ensureMeetScope78();toast('Jivan is reading the authorized Google Meet transcript and preparing interview notes…');const r=await meetInterviewRequest78({action:'analyze',interview_id:id});if(!r?.note)throw new Error('Interview notes were not returned.');showInterviewNote78(r.note);toast(r.cached?'Existing Jivan interview notes opened.':'Jivan interview notes generated.');}catch(err){toast(err.message||String(err));}finally{meetAssistantBusy78=false;}}
  function showInterviewComparison78(rows=[]){const d=ensureMeetNoteDialog78();$('meetInterviewNoteTitle78').textContent='Interview evidence comparison';$('meetInterviewNoteBody78').innerHTML=`<div class="meet-note78-warning">This is a side-by-side evidence review, not a ranking or hiring recommendation. Apply the same approved job criteria to every candidate and make the final decision through HR/panel governance.</div><div class="meet-compare78-list">${rows.length?rows.map(row=>{const a=row.analysis||{};return `<article class="meet-compare78-person"><h4>${esc(row.candidate_name||a.candidate||'Candidate')}</h4><small>${esc(a.summary||'No summary.')}</small>${(a.criteria||[]).map(x=>`<div class="meet-note78-criterion"><b>${esc(x.criterion||'Criterion')}</b><span class="meet-note78-status">${esc(x.status||'')}</span><span>${esc(x.evidence||'')}</span></div>`).join('')}</article>`;}).join(''):'<div class="meet-note78-card"><p>No Jivan interview notes have been generated for this vacancy yet.</p></div>'}</div>`;d.showModal();}
  async function compareInterviewEvidence78(){const vacancyId=String(state.recruitVacancy||'');if(!vacancyId)return toast('Select one vacancy first.');try{const r=await meetInterviewRequest78({action:'compare',vacancy_id:vacancyId,company_id:currentCompanyId?.()||''});showInterviewComparison78(r?.candidates||[]);}catch(err){toast(err.message||String(err));}}
  document.addEventListener('click',e=>{const notes=e.target.closest('[data-jivan-interview-notes78]'),connect=e.target.closest('[data-meet-connect78]'),compare=e.target.closest('[data-meet-compare78]'),close=e.target.closest('[data-meet-note-close78]');if(notes){e.preventDefault();analyzeInterview78(notes.dataset.jivanInterviewNotes78||'');}else if(connect){e.preventDefault();authorizeMeetScope78().catch(err=>toast(err.message||String(err)));}else if(compare){e.preventDefault();compareInterviewEvidence78();}else if(close){e.preventDefault();$('meetInterviewNoteDialog78')?.close();}});
  const baseRenderRecruiting78=renderRecruiting;
  renderRecruiting=function(){const r=baseRenderRecruiting78();setTimeout(()=>renderMeetInterviewAssistant78(),0);return r;};
  window.addEventListener('focus',()=>{if(browserSessionToken&&state.view==='recruitment')loadMeetAssistantStatus78(true).then(()=>renderMeetInterviewAssistant78()).catch(()=>{});});
  /* Assurance Regent v6.3.78 — Google Meet Jivan interview assistant END */
