  /* Assurance Regent v6.3.105 — HR recruitment selections to onboarding START */
  const RECRUITMENT_SELECTIONS_SCHEMA105='6.3.105';
  let recruitSelectionBusy105=false;

  function selectionRows105(){return Array.isArray(recruitmentBundle().selections)?recruitmentBundle().selections:[];}
  function interviewEvaluationRows105(){return Array.isArray(recruitmentBundle().interviewEvaluations)?recruitmentBundle().interviewEvaluations:[];}
  function selectionForApplication105(id){return selectionRows105().find(x=>String(x.application_id)===String(id))||null;}
  function selectionActive105(row){return Boolean(row&&['SELECTED','ONBOARDING_SENT'].includes(String(row.status||'').toUpperCase()));}
  function selectionVisibleApplications105(){let rows=newestFirst(recruitmentBundle().applications||[],['applied_at','updated_at']);if(state.recruitVacancy)rows=rows.filter(a=>String(a.vacancy_id)===String(state.recruitVacancy));return rows;}
  function selectionChosenApplications105(){return selectionVisibleApplications105().filter(a=>selectionActive105(selectionForApplication105(a.id)));}
  function selectionInterview105(applicationId){return newestFirst((recruitmentBundle().interviews||[]).filter(i=>String(i.application_id)===String(applicationId)),['scheduled_at','created_at'])[0]||null;}
  function selectionEvaluation105(applicationId){return newestFirst(interviewEvaluationRows105().filter(x=>String(x.application_id)===String(applicationId)),['generated_at','updated_at'])[0]||null;}
  function numericScore105(value){const n=Number(value);if(!Number.isFinite(n)||n<0)return null;if(n<=1)return Math.round(n*100);if(n<=100)return Math.round(n);return null;}
  function interviewScore105(applicationId){const row=selectionEvaluation105(applicationId),a=row?.analysis;if(!a||typeof a!=='object')return null;const containers=[a,a.interview,a.evaluation,a.assessment,a.summary,a.candidate].filter(x=>x&&typeof x==='object');for(const obj of containers){for(const key of ['overall_score','overallScore','performance_score','performanceScore','interview_score','interviewScore','score_percent','scorePercent','percentage']){const score=numericScore105(obj?.[key]);if(score!==null)return score;}}return null;}
  function selectionPerformanceCell105(app){const interview=selectionInterview105(app.id),score=interviewScore105(app.id);if(score!==null)return `<div class="selection-performance"><strong>${score}%</strong><small>Interview evaluation</small></div>`;if(!interview)return '<span class="muted">Not interviewed</span>';const status=String(interview.status||'').toUpperCase();if(status==='COMPLETED')return '<div class="selection-performance"><strong>Completed</strong><small>Score not recorded</small></div>';if(status==='SCHEDULED')return `<div class="selection-performance"><strong>Scheduled</strong><small>${esc(new Date(interview.scheduled_at).toLocaleString())}</small></div>`;return `<div class="selection-performance"><strong>${esc(interview.status||'Interview')}</strong><small>Interview status</small></div>`;}
  function selectionFitCell105(app){const score=numericScore105(app.ai_score);if(score===null)return '<span class="muted">Not reviewed</span>';return `<div class="selection-performance"><strong>${score}%</strong><small>Advisory fit · rank ${esc(app.ai_rank||'—')}</small></div>`;}
  function selectionStatusCell105(app){const s=selectionForApplication105(app.id);if(!s||String(s.status).toUpperCase()==='DESELECTED')return '<span class="employee-status pending">Not selected</span>';if(String(s.status).toUpperCase()==='ONBOARDING_SENT')return '<span class="employee-status active">Sent to onboarding</span>';return '<span class="employee-status active">HR selected</span>';}
  function setSelectionBusy105(active,label=''){recruitSelectionBusy105=Boolean(active);for(const id of ['recruitSelectionsEmail','recruitSelectionsWhatsApp','recruitSelectionsOnboarding']){const b=$(id);if(b)b.disabled=recruitSelectionBusy105;}if(label&&$('recruitSelectionSummary'))$('recruitSelectionSummary').textContent=label;}
  function safeSelectionOutreachUrl105(value=''){try{const u=new URL(String(value||''),location.href);return ['https:','mailto:'].includes(u.protocol)?u.href:'';}catch{return '';}}
  function renderSelectionDelivery105(items=[]){const el=$('recruitSelectionDelivery');if(!el)return;el.hidden=!items.length;el.innerHTML=items.length?`<b>Delivery actions requiring your browser</b><div>${items.map(x=>`<a class="btn micro secondary" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Open ${esc(x.channel)} · ${esc(x.name)}</a>`).join('')}</div>`:'';}

  function renderRecruitSelections105(){
    const table=$('recruitSelectionsTable');if(!table)return;const hr=recruitmentHrAllowed();const tab=document.querySelector('[data-recruit-tab="selections"]');if(tab)tab.hidden=!hr;if(!hr){table.innerHTML='';return;}
    const rows=selectionVisibleApplications105(),activeCount=rows.filter(a=>selectionActive105(selectionForApplication105(a.id))).length,totalActive=selectionRows105().filter(selectionActive105).length;
    if($('recruitSelectionCount'))$('recruitSelectionCount').textContent=String(totalActive);
    if($('recruitSelectionSummary'))$('recruitSelectionSummary').textContent=`${activeCount} selected in this view · HR makes the final selection decision`;
    const html=rows.length?rows.map(a=>{const selected=selectionForApplication105(a.id),checked=selectionActive105(selected),sent=String(selected?.status||'').toUpperCase()==='ONBOARDING_SENT';return `<tr><td class="selection-check-cell"><input type="checkbox" data-selection-application="${esc(a.id)}" ${checked?'checked':''} ${sent?'disabled title="Already sent to onboarding"':''} aria-label="Select ${esc(a.applicant_name)}" /></td><td><b>${esc(a.applicant_name)}</b><small class="table-subline">${esc(a.email||'')}${a.phone?` · ${esc(a.phone)}`:''}</small></td><td><b>${esc(a.vacancy_title||'—')}</b><small class="table-subline">${esc(a.qualification||a.vacancy_id||'')}</small></td><td>${selectionFitCell105(a)}</td><td>${selectionPerformanceCell105(a)}</td><td>${directoryStatusChip(a.status||'NEW')}</td><td>${selectionStatusCell105(a)}</td></tr>`;}).join(''):'<tr class="empty-row"><td colspan="7"><div class="table-empty"><b>No applicants available for selection</b><span>Applications will appear here automatically once they enter the recruitment system.</span></div></td></tr>';
    table.innerHTML=`<thead><tr><th class="selection-check-cell"><input type="checkbox" id="recruitSelectionSelectAll" aria-label="Select all visible applicants" /></th><th>Applicant</th><th>Vacancy / qualification</th><th>AI fit score</th><th>Interview performance</th><th>Application status</th><th>Selection status</th></tr></thead><tbody>${html}</tbody>`;
    const all=$('recruitSelectionSelectAll'),eligible=rows.filter(a=>String(selectionForApplication105(a.id)?.status||'').toUpperCase()!=='ONBOARDING_SENT');if(all){all.checked=Boolean(eligible.length&&eligible.every(a=>selectionActive105(selectionForApplication105(a.id))));all.indeterminate=Boolean(eligible.some(a=>selectionActive105(selectionForApplication105(a.id)))&&!all.checked);all.disabled=!eligible.length;}
  }

  async function updateRecruitSelections105(ids,selected){
    if(recruitSelectionBusy105||!ids.length)return;setSelectionBusy105(true,selected?'Saving HR selections…':'Updating HR selections…');try{await supabaseRpc('assurance_regent_browser_recruitment_selection_update',{p_token:browserSessionToken,p_application_ids:ids,p_selected:Boolean(selected)},{bypassCache:true});await loadRecruitmentBundle(true);renderRecruiting();}catch(err){toast(err.message);}finally{setSelectionBusy105(false);renderRecruitSelections105();}
  }

  function selectionMessage105(app,channel){const company=activeCompanyForView()||{},companyName=String(company.name||company.companyName||'the organization').trim()||'the organization',role=String(app.vacancy_title||'the position').trim();const greeting=`Dear ${app.applicant_name||'Candidate'},`;const body=`We are pleased to inform you that you have been selected to progress to the onboarding process for ${role} at ${companyName}. Our Human Resources team will guide you through the next onboarding steps and required documentation.`;return channel==='whatsapp'?`${greeting}\n\n${body}\n\nRegards,\nHuman Resources · ${companyName}`:`${greeting}\n\n${body}\n\nRegards,\nHuman Resources\n${companyName}`;}
  async function sendRecruitSelectionOutreach105(channel){
    if(recruitSelectionBusy105)return;const apps=selectionChosenApplications105();if(!apps.length)return toast('Select at least one applicant first.');const label=channel==='email'?'email':'WhatsApp';if(!confirm(`Send the selection ${label} message to ${apps.length} selected candidate${apps.length===1?'':'s'}?`))return;setSelectionBusy105(true,`Sending ${label} selection messages…`);const fallbacks=[];let sent=0,failed=0;
    try{for(const app of apps){try{const subject=`Selection confirmation — ${app.vacancy_title||'next onboarding step'}`,message=selectionMessage105(app,channel),result=await supabaseFunction('recruitment-public',{action:'hr_send_outreach',application_id:app.id,channel,message,subject,interview_url:''});if(result?.sent)sent++;else{const url=safeSelectionOutreachUrl105(result?.url||'');if(url)fallbacks.push({url,name:app.applicant_name||'Candidate',channel:label});else failed++;}}catch{failed++;}}renderSelectionDelivery105(fallbacks);const prepared=fallbacks.length;toast(`${sent} ${label} message${sent===1?'':'s'} sent${prepared?`; ${prepared} prepared for browser delivery`:''}${failed?`; ${failed} failed`:''}.`);}finally{setSelectionBusy105(false);renderRecruitSelections105();}
  }

  async function ensureSelectionCandidate105(app){
    let candidate=engine.state.candidates.find(c=>String(c.id)===String(app.candidate_id||''))||engine.state.candidates.find(c=>String(c.email||'').toLowerCase()===String(app.email||'').toLowerCase()&&String(c.vacancyId||'')===String(app.vacancy_id||''));const vacancy=engine.state.vacancies.find(v=>String(v.id)===String(app.vacancy_id));
    if(!candidate){candidate=engine.upsertCandidate({companyId:app.company_id||currentCompanyId(),name:app.applicant_name,email:app.email,phone:app.phone,vacancyId:app.vacancy_id,jobTitle:app.vacancy_title||vacancy?.title||'',department:vacancy?.department||'',location:app.location||vacancy?.location||'',employmentType:vacancy?.employmentType||'Full Time',stage:'Selected',status:'Active',appliedDate:String(app.applied_at||'').slice(0,10),notes:[app.cover_note,'Selected by Human Resources for onboarding.'].filter(Boolean).join('\n\n')});await supabaseRpc('assurance_regent_browser_recruitment_application_imported',{p_token:browserSessionToken,p_application_id:app.id,p_candidate_id:candidate.id},{bypassCache:true});}
    if(candidate.stage!=='Offer Accepted')candidate=engine.upsertCandidate({...candidate,stage:'Selected',status:'Active'});return candidate;
  }

  async function sendRecruitSelectionsToOnboarding105(){
    if(recruitSelectionBusy105)return;const apps=selectionChosenApplications105().filter(a=>String(selectionForApplication105(a.id)?.status||'').toUpperCase()!=='ONBOARDING_SENT');if(!apps.length)return toast('Select at least one applicant who has not already been sent to onboarding.');if(!confirm(`Send ${apps.length} selected candidate${apps.length===1?'':'s'} to Onboarding?`))return;setSelectionBusy105(true,'Transferring selected candidates to Onboarding…');let moved=0;
    try{for(const app of apps){const candidate=await ensureSelectionCandidate105(app);await supabaseRpc('assurance_regent_browser_recruitment_selection_onboarding',{p_token:browserSessionToken,p_application_id:app.id,p_candidate_id:candidate.id},{bypassCache:true});moved++;}persistLocalLiveState();await loadRecruitmentBundle(true);renderRecruiting();renderOnboarding();toast(`${moved} selected candidate${moved===1?'':'s'} received by Onboarding.`);}catch(err){toast(err.message);}finally{setSelectionBusy105(false);renderRecruitSelections105();}
  }

  const renderRecruitingBeforeSelections105=renderRecruiting;
  renderRecruiting=function(){if(!recruitmentHrAllowed()&&state.recruitTab==='selections')state.recruitTab='funnel';renderRecruitingBeforeSelections105();const panels=['recruitPanelVacancies','recruitPanelApplications','recruitPanelCandidates','recruitPanelInterviews','recruitPanelFunnel','recruitPanelAnalytics','recruitPanelSelections'];if(state.recruitTab==='selections'){for(const id of panels)$(id)?.classList.remove('active');$('recruitPanelSelections')?.classList.add('active');}renderRecruitSelections105();};

  const renderOnboardingBeforeSelections105=renderOnboarding;
  renderOnboarding=function(){renderOnboardingBeforeSelections105();const select=$('onboardingCandidateSelect');if(!select)return;const eligible=engine.state.candidates.filter(c=>['Selected','Offer Accepted'].includes(c.stage)&&String(c.status||'Active').toLowerCase()!=='hired');select.innerHTML=eligible.length?'<option value="">Select candidate received from Recruitment</option>'+eligible.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} · ${esc(vacancyForCandidate(c)?.title||c.jobTitle||c.stage)} · ${esc(c.stage)}</option>`).join(''):'<option value="">No selected candidates received</option>';const kicker=document.querySelector('#view-onboarding .onboarding-start-bar .section-kicker');if(kicker)kicker.textContent='Recruitment selection → employee master';};

  document.addEventListener('change',e=>{const row=e.target.closest?.('[data-selection-application]');if(row){updateRecruitSelections105([row.dataset.selectionApplication],row.checked);return;}if(e.target?.id==='recruitSelectionSelectAll'){const ids=selectionVisibleApplications105().filter(a=>String(selectionForApplication105(a.id)?.status||'').toUpperCase()!=='ONBOARDING_SENT').map(a=>a.id);updateRecruitSelections105(ids,e.target.checked);}});
  document.addEventListener('click',e=>{if(e.target.closest?.('#recruitSelectionsEmail'))sendRecruitSelectionOutreach105('email');else if(e.target.closest?.('#recruitSelectionsWhatsApp'))sendRecruitSelectionOutreach105('whatsapp');else if(e.target.closest?.('#recruitSelectionsOnboarding'))sendRecruitSelectionsToOnboarding105();});

  window.AssuranceRegentRecruitmentSelections={schema:RECRUITMENT_SELECTIONS_SCHEMA105,humanDecision:true,automaticSelection:false,persisted:true,email:true,whatsapp:true,onboardingTransfer:true,scoreUse:'display-only'};
  /* Assurance Regent v6.3.105 — HR recruitment selections to onboarding END */
