  /* Assurance Regent v6.3.43 — governed multi-format reports + Internal Auditor advanced tools. */
  const REPORT_CATALOG=Object.freeze({
    executive:{label:'Executive overview',title:'Executive Overview Report'},
    payroll:{label:'Payroll',title:'Payroll Report'},
    employees:{label:'Employee master',title:'Employee Master Report'},
    work:{label:'Work activity',title:'Work Activity Report'},
    time:{label:'Recovery time entries',title:'Recovery Time Entry Report'},
    projects:{label:'Projects',title:'Project Register Report'},
    monthly:{label:'Monthly recovery engine',title:'Monthly Recovery Engine Report'},
    checks:{label:'Control checks',title:'Control Checks Report'},
    recovery:{label:'Recovery assurance',title:'Recovery Assurance Report'},
    vacancies:{label:'Vacancies',title:'Vacancy Report'},
    candidates:{label:'Recruitment candidates',title:'Recruitment Candidate Report'},
    onboarding:{label:'Onboarding',title:'Onboarding Progress Report'},
    calendar:{label:'Calendar',title:'Operational Calendar Report'},
    audit:{label:'Internal audit findings',title:'Internal Audit Findings Report'}
  });
  function reportAuthority(){return functionalAuthority(effectiveUserOrg(controlUser()||{}));}
  function reportAllowedKinds(){
    const a=reportAuthority();
    if(['DEVELOPER','CEO','ADMINISTRATOR'].includes(a))return Object.keys(REPORT_CATALOG).filter(x=>x!=='audit');
    if(a==='AUDITOR')return ['executive','payroll','employees','work','time','projects','monthly','checks','recovery','audit'];
    if(a==='FINANCE_MANAGER')return ['executive','payroll','time','projects','monthly','checks','recovery'];
    if(a==='HR_MANAGER')return ['executive','employees','vacancies','candidates','onboarding','calendar'];
    if(['PROJECT_MANAGER','PROGRAMS_MANAGER'].includes(a))return ['executive','employees','work','time','projects','calendar'];
    return ['executive'];
  }
  function reportMonthValue(v){const s=String(v||'');if(/^\d{4}-\d{2}/.test(s))return s.slice(0,7);const d=new Date(v);return Number.isNaN(d.getTime())?'':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
  function reportPeriodRows(rows,keys,period='selected'){if(period!=='selected')return rows;const month=String(state.month||'').slice(0,7);return rows.filter(r=>keys.some(k=>reportMonthValue(r?.[k])===month));}
  function reportCompanyScope(rows){const a=reportAuthority(),cid=String(currentCompanyId?.()||controlUser()?.companyId||'');if(a==='DEVELOPER')return [...(rows||[])];return (rows||[]).filter(r=>{const rc=String(r?.companyId||r?.company_id||'');return !rc||!cid||rc===cid;});}
  function reportEmployeeScope(rows){const a=reportAuthority();if(['AUDITOR','DEVELOPER','CEO','ADMINISTRATOR','HR_MANAGER'].includes(a))return reportCompanyScope(rows);return scopeEmployeeRows(reportCompanyScope(rows));}
  function reportCell(v){if(v===null||v===undefined)return '';if(typeof v==='object')return JSON.stringify(v);return String(v);}
  function reportNormalize(rows,columns){return (rows||[]).map(r=>Object.fromEntries(columns.map(([label,key,transform])=>[label,transform?transform(r?.[key],r):reportCell(r?.[key])])));}
  function reportExecutiveRows(){const d=engine.dashboard(),pay=engine.payrollAnalysis(),work=reportCompanyScope(state.mtsSessions||[]),cands=engine.state.candidates||[];return [{
    'Reporting month':window.ADRAEngine?.monthLabel?.(state.month)||state.month,
    'Employees':reportCompanyScope(engine.state.employees||[]).length,
    'Active work sessions':work.filter(x=>String(x.status||'').toLowerCase()==='active').length,
    'Completed work sessions':work.filter(x=>String(x.status||'').toLowerCase()==='completed').length,
    'Projects':reportCompanyScope(engine.state.projects||[]).length,
    'Payroll records':reportCompanyScope(pay).length,
    'Candidates':reportCompanyScope(cands).length,
    'Recovery periods':d.monthly?.length||0,
    'Periods ready to post':d.monthsReadyToPost||0
  }];}
  async function reportDataset(kind,period='selected'){
    if(!reportAllowedKinds().includes(kind))throw new Error('This report is outside your permitted authority.');
    if(kind==='executive')return reportExecutiveRows();
    if(kind==='payroll'){
      const rows=reportPeriodRows(reportCompanyScope(engine.payrollAnalysis()),['month'],period);
      return reportNormalize(rows,[['Month','month',(v)=>window.ADRAEngine?.monthLabel?.(v)||v],['Employee ID','employeeId'],['Basic salary','basicSalary'],['Benefits','benefits'],['Statutory cost','statutoryCost'],['Exclusions','exclusions'],['Allocable cost','allocableCost'],['Configuration','configurationStatus'],['Source','source']]);
    }
    if(kind==='employees')return reportNormalize(reportEmployeeScope(engine.state.employees||[]),[['Employee ID','employeeId'],['Name','name'],['Position','position'],['Department','department'],['Team','team'],['Supervisor','supervisor'],['Employment type','employmentType'],['Status','employmentStatus'],['Location','location'],['Email','email'],['Phone','phone']]);
    if(kind==='work'){
      let rows=reportPeriodRows(reportCompanyScope(state.mtsSessions||[]),['work_date','clock_in_at'],period);const a=reportAuthority();if(!['AUDITOR','DEVELOPER','CEO','ADMINISTRATOR'].includes(a))rows=scopeMtsRows(rows);
      return reportNormalize(rows,[['Date','work_date'],['Employee ID','employee_id'],['Employee','employee_name'],['Department','department'],['Project','project_code'],['Activity','activity_description'],['Clock in','clock_in_at'],['Clock out','clock_out_at'],['Hours','duration_hours'],['Completion %','completion_percent'],['Status','status'],['Document','document_name']]);
    }
    if(kind==='time'){
      const rows=reportPeriodRows(reportCompanyScope(engine.analyzedTimeEntries()),['month','date','work_date'],period);
      return reportNormalize(rows,[['Entry ID','entryId'],['Date','date'],['Month','month'],['Employee ID','employeeId'],['Employee','employeeName'],['Project','projectCode'],['Activity evidence','activity'],['Hours','hours'],['Time type','timeType'],['Status','status'],['Eligibility','projectEligibility'],['Entry assurance','entryAssurance']]);
    }
    if(kind==='projects')return reportNormalize(reportCompanyScope(engine.state.projects||[]),[['Code','code'],['Project','name'],['Donor','donor'],['Start','startDate'],['End','endDate'],['Status','status'],['Personnel budget','personnelBudget'],['Eligible employee','eligibleEmployeeId'],['Administration allowed','adminAllowed']]);
    if(kind==='monthly'){
      const rows=reportPeriodRows(engine.monthlyEngine(),['month'],period);return rows.map(r=>Object.fromEntries(Object.entries(r).filter(([k])=>!['profilePhoto','data'].includes(k))));
    }
    if(kind==='checks'){
      const checks=engine.checks(),rows=reportPeriodRows(checks?.rows||[],['month'],period);return rows.map(r=>({...r}));
    }
    if(kind==='vacancies')return reportNormalize(reportCompanyScope(engine.state.vacancies||[]),[['Vacancy ID','id'],['Reference','reference'],['Title','title'],['Department','department'],['Location','location'],['Type','employmentType'],['Status','status'],['Open date','openDate'],['Deadline','closeDate']]);
    if(kind==='candidates')return reportNormalize(reportCompanyScope(engine.state.candidates||[]),[['Candidate ID','id'],['Name','name'],['Job title','jobTitle'],['Department','department'],['Stage','stage'],['Status','status'],['Applied','appliedDate'],['Email','email'],['Phone','phone']]);
    if(kind==='onboarding')return reportNormalize(reportCompanyScope(engine.state.onboarding||[]),[['ID','id'],['Candidate','candidateName'],['Employee ID','employeeId'],['Job title','jobTitle'],['Department','department'],['Step','step'],['Status','status'],['Start date','startDate']]);
    if(kind==='calendar'){
      const rows=reportPeriodRows(reportCompanyScope(engine.state.calendar||[]),['date','start','startDate'],period);return rows.map(r=>({...r}));
    }
    if(kind==='recovery'){
      await loadRecoveryAssurance(true);const rows=reportPeriodRows(recoveryComputedPassports(),['reportingMonth'],period);return rows.map(r=>({'Month':r.reportingMonth,'Employee ID':r.employeeId,'Employee':r.employee,'Project':r.projectCode,'Donor':r.donor,'Approved hours':r.approvedProjectHours,'Raw cost':r.rawCost,'Recovery gate':r.finalStatus,'Recoverable':r.recoverableCost,'Amount at risk':r.amountAtRisk,'Five-key result':recoveryKeySummary(r)}));
    }
    if(kind==='audit'){
      if(reportAuthority()!=='AUDITOR')throw new Error('Advanced audit findings are restricted to Internal Auditor authority.');return advancedAuditorFindings($('advancedAuditScope')?.value||'ALL');
    }
    return [];
  }
  function reportHeaders(rows){return [...new Set((rows||[]).flatMap(r=>Object.keys(r||{})))].filter(h=>!/(password|secret|token|profilephoto|data$)/i.test(h));}
  function reportTableHtml(rows,limit=25){const headers=reportHeaders(rows),view=rows.slice(0,limit);if(!view.length)return '<div class="table-empty"><b>No records for this report</b><span>Change the reporting period or add live data.</span></div>';return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${view.map(r=>`<tr>${headers.map(h=>`<td>${esc(reportCell(r[h]))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
  function reportExcelBlob(title,rows){const headers=reportHeaders(rows),xmlEsc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const table=`<table><tr>${headers.map(h=>`<th>${xmlEsc(h)}</th>`).join('')}</tr>${rows.map(r=>`<tr>${headers.map(h=>`<td>${xmlEsc(reportCell(r[h]))}</td>`).join('')}</tr>`).join('')}</table>`;return new Blob([`<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="UTF-8"><title>${xmlEsc(title)}</title></head><body><h2>${xmlEsc(title)}</h2><p>Generated ${xmlEsc(new Date().toLocaleString())}</p>${table}</body></html>`],{type:'application/vnd.ms-excel'});}
  function reportWordBlob(title,rows){return new Blob([agentWordHtml(title,rows)],{type:'application/msword'});}
  function reportPdfBlob(title,rows){
    const ascii=v=>String(v??'').normalize('NFKD').replace(/[^\x20-\x7E]/g,'?'),pdfEsc=v=>ascii(v).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)'),headers=reportHeaders(rows);
    const raw=[ascii(title),`Generated ${ascii(new Date().toLocaleString())}`,`Rows: ${rows.length}`,''];
    rows.forEach((r,i)=>{let line=`${i+1}. `+headers.map(h=>`${h}: ${reportCell(r[h])}`).join(' | ');while(line.length>112){raw.push(line.slice(0,112));line='   '+line.slice(112);}raw.push(line);});
    const pageLines=48,pages=[];for(let i=0;i<raw.length;i+=pageLines)pages.push(raw.slice(i,i+pageLines));if(!pages.length)pages.push([ascii(title),'No records.']);
    const objects=[];objects[1]='<< /Type /Catalog /Pages 2 0 R >>';objects[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';const kids=[];
    pages.forEach((lines,i)=>{const pageObj=4+i*2,contentObj=5+i*2,kids.push(`${pageObj} 0 R`),stream=['BT','/F1 7 Tf','30 812 Td','10.5 TL',...lines.map((line,j)=>`${j?'T* ':''}(${pdfEsc(line)}) Tj`),'ET'].join('\n');objects[pageObj]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentObj} 0 R >>`;objects[contentObj]=`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`;});objects[2]=`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${kids.length} >>`;
    let pdf='%PDF-1.4\n',offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`;}const xref=pdf.length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'});
  }
  async function createGovernedReport(kind,period,format,rows=null){const catalog=REPORT_CATALOG[kind];if(!catalog)throw new Error('Select a valid report.');const data=rows||await reportDataset(kind,period);if(!data.length)throw new Error('There are no live records for the selected report and period.');const stamp=new Date().toISOString().slice(0,10),month=period==='selected'?`-${String(state.month||'').slice(0,7)}`:'-all-periods',slug=kind.replace(/[^a-z0-9-]/gi,'-').toLowerCase(),fmt=String(format||'excel').toLowerCase();let blob,name;if(fmt==='pdf'){blob=reportPdfBlob(catalog.title,data);name=`assurance-regent-${slug}${month}-${stamp}.pdf`;}else if(fmt==='word'){blob=reportWordBlob(catalog.title,data);name=`assurance-regent-${slug}${month}-${stamp}.doc`;}else{blob=reportExcelBlob(catalog.title,data);name=`assurance-regent-${slug}${month}-${stamp}.xls`;}
    const stored=await uploadPersistentBlob(blob,name,{category:'generated-reports',entityType:'system-report',entityId:`${kind}:${period}`,metadata:{reportKind:kind,format:fmt,period,rows:data.length,generatedBy:controlActorId(),authority:reportAuthority()}});const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);toast(`${catalog.label} report generated, stored in Supabase and downloaded.`);return {name,rows:data.length,fileId:stored.fileId,format:fmt};}
  async function renderReportGenerator(){const type=$('systemReportType'),period=$('systemReportPeriod'),preview=$('systemReportPreview');if(!type||!preview)return;const allowed=reportAllowedKinds(),current=allowed.includes(type.value)?type.value:allowed[0];type.innerHTML=allowed.map(k=>`<option value="${k}"${k===current?' selected':''}>${esc(REPORT_CATALOG[k].label)}</option>`).join('');if(!type.value&&allowed.length)type.value=allowed[0];try{const rows=await reportDataset(type.value,period?.value||'selected');preview.innerHTML=`<div class="report-generator-meta"><span><b>${rows.length}</b> row${rows.length===1?'':'s'}</span><span><b>${esc(REPORT_CATALOG[type.value]?.label||'Report')}</b></span><span>${period?.value==='all'?'All available periods':esc(window.ADRAEngine?.monthLabel?.(state.month)||state.month)}</span><span>Authority: <b>${esc(authorityLabel(reportAuthority()))}</b></span></div>${reportTableHtml(rows,18)}`;}catch(err){preview.innerHTML=`<div class="table-empty"><b>Report preview unavailable</b><span>${esc(err.message||'Unable to prepare report.')}</span></div>`;}}
  async function generateSelectedSystemReport(){const btn=$('systemReportGenerate');if(!btn)return;btn.disabled=true;const old=btn.textContent;btn.textContent='Generating…';try{await createGovernedReport($('systemReportType').value,$('systemReportPeriod').value,$('systemReportFormat').value);}catch(err){toast(err.message||'Could not generate this report.');}finally{btn.disabled=false;btn.textContent=old;}}

  function advancedAuditorAllowed(){return reportAuthority()==='AUDITOR';}
  function auditPush(out,scope,control,record,finding,risk='MEDIUM',action='Review the underlying evidence and document the audit conclusion.'){out.push({Scope:scope,Control:control,Record:record||'—',Finding:finding,Risk:risk,'Required action':action});}
  function advancedAuditorFindings(scope='ALL'){
    if(!advancedAuditorAllowed())return [];
    const want=s=>scope==='ALL'||scope===s,out=[],employees=reportCompanyScope(engine.state.employees||[]),empIds=new Set(employees.map(e=>String(e.employeeId||e.id||'').trim().toLowerCase()).filter(Boolean)),projects=reportCompanyScope(engine.state.projects||[]),projectIds=new Set(projects.map(p=>String(p.code||p.projectCode||p.id||'').trim().toLowerCase()).filter(Boolean));
    if(want('EMPLOYEES')){const seen=new Map();for(const e of employees){const id=String(e.employeeId||e.id||'').trim().toLowerCase();if(id)seen.set(id,(seen.get(id)||0)+1);}for(const [id,n] of seen)if(n>1)auditPush(out,'Employee master','Duplicate employee ID',id,`${n} employee master records use the same ID.`,'HIGH','Resolve the duplicate master records and preserve the approved source record.');for(const e of employees)if(!String(e.name||'').trim())auditPush(out,'Employee master','Missing employee identity',e.employeeId||e.id,'Employee name is blank.','MEDIUM');}
    if(want('PAYROLL')){const rows=reportCompanyScope(engine.payrollAnalysis()),seen=new Map();for(const r of rows){const key=`${reportMonthValue(r.month)}|${String(r.employeeId||'').toLowerCase()}`;seen.set(key,(seen.get(key)||0)+1);const expected=Number(r.basicSalary||0)+Number(r.benefits||0)+Number(r.statutoryCost||0)-Number(r.exclusions||0);if(Math.abs(expected-Number(r.allocableCost||0))>.01)auditPush(out,'Payroll','Payroll formula recalculation',key,`Allocable cost ${r.allocableCost} differs from recomputed ${expected.toFixed(2)}.`,'HIGH','Reconcile payroll components to the authorized source payroll.');if([r.basicSalary,r.benefits,r.statutoryCost,r.exclusions,r.allocableCost].some(v=>Number(v)<0))auditPush(out,'Payroll','Negative payroll component',key,'A payroll component contains a negative amount.','HIGH');if(String(r.configurationStatus||'').toUpperCase()==='REVIEW')auditPush(out,'Payroll','Payroll configuration',key,'Payroll row remains in REVIEW configuration.','HIGH','Complete authorized payroll configuration before cost recovery.');if(r.employeeId&&!empIds.has(String(r.employeeId).toLowerCase()))auditPush(out,'Payroll','Employee master cross-check',key,'Payroll employee ID is not present in the current employee master.','HIGH');}for(const [key,n] of seen)if(n>1)auditPush(out,'Payroll','Duplicate employee-month payroll',key,`${n} payroll rows exist for the same employee and month.`,'HIGH');}
    if(want('WORK')){for(const r of reportCompanyScope(state.mtsSessions||[])){const ref=r.id||`${r.employee_id}|${r.work_date}`;if(r.employee_id&&!empIds.has(String(r.employee_id).toLowerCase()))auditPush(out,'Work evidence','Employee master cross-check',ref,'Work session employee ID is not present in the employee master.','HIGH');if(Number(r.duration_hours||0)<0||Number(r.duration_hours||0)>24)auditPush(out,'Work evidence','Duration bounds',ref,`Duration ${r.duration_hours} hours is outside 0–24 hours.`,'HIGH');if(String(r.status||'').toLowerCase()==='completed'&&!String(r.activity_description||'').trim())auditPush(out,'Work evidence','Activity evidence completeness',ref,'Completed work session has no activity description.','MEDIUM');if(r.project_code&&!projectIds.has(String(r.project_code).toLowerCase()))auditPush(out,'Work evidence','Project master cross-check',ref,`Project ${r.project_code} is not present in the project master.`,'HIGH');}}
    if(want('TIME')){for(const r of reportCompanyScope(engine.analyzedTimeEntries())){const ref=r.entryId||r.id||`${r.employeeId}|${r.date}`;if(Number(r.hours||0)<=0||Number(r.hours||0)>24)auditPush(out,'Recovery time','Time-entry bounds',ref,`Recorded hours ${r.hours} are outside the permitted daily range.`,'HIGH');if(r.employeeId&&!empIds.has(String(r.employeeId).toLowerCase()))auditPush(out,'Recovery time','Employee master cross-check',ref,'Time-entry employee ID is not in the employee master.','HIGH');if(r.projectCode&&!projectIds.has(String(r.projectCode).toLowerCase()))auditPush(out,'Recovery time','Project master cross-check',ref,`Project ${r.projectCode} is not present in the project master.`,'HIGH');if(String(r.projectEligibility||'').toUpperCase()==='BLOCK')auditPush(out,'Recovery time','Project eligibility',ref,'Project eligibility is BLOCK.','HIGH','Resolve eligibility against the approved project and donor rules; do not override the control.');}}
    if(want('PROJECTS')){for(const p of projects){const ref=p.code||p.id;if(!String(p.name||'').trim())auditPush(out,'Projects','Project master completeness',ref,'Project name is blank.','MEDIUM');if(p.personnelBudget!==undefined&&Number(p.personnelBudget)<0)auditPush(out,'Projects','Personnel budget validity',ref,'Personnel budget is negative.','HIGH');}}
    if(want('CONTROLS')){const checks=engine.checks()?.rows||[];for(const c of checks)if(String(c.result||'').toUpperCase()==='FAIL')auditPush(out,'System controls',c.check||c.name||'Control check',c.month||c.id||'—',c.whereToFix||c.detail||'A deterministic system check failed.',String(c.severity||'HIGH').toUpperCase()==='LOW'?'LOW':String(c.severity||'HIGH').toUpperCase()==='MEDIUM'?'MEDIUM':'HIGH','Reconcile the failed control to source evidence and document resolution.');const users=state.control?.profile?.users||[],ids=new Map();for(const u of users){const id=String(u.id||'').toLowerCase();if(id)ids.set(id,(ids.get(id)||0)+1);}for(const [id,n] of ids)if(n>1)auditPush(out,'Access & SoD','Duplicate user identifier',id,`${n} accounts share the same user identifier.`,'HIGH');}
    if(want('RECOVERY')){for(const t of recoveryAuditTests().filter(x=>x.result==='FAIL'))auditPush(out,'Recovery assurance',t.name,t.scope,`${t.exceptions} exception(s). ${t.action}`,t.risk||'HIGH',t.action);}
    return out;
  }
  function renderAdvancedAuditorTools(){const suite=$('advancedAuditorSuite');if(!suite)return;const allowed=advancedAuditorAllowed();suite.hidden=!allowed;if(!allowed)return;const scope=$('advancedAuditScope')?.value||'ALL',rows=advancedAuditorFindings(scope),high=rows.filter(x=>x.Risk==='HIGH').length,medium=rows.filter(x=>x.Risk==='MEDIUM').length,k=$('advancedAuditKpis');if(k)k.innerHTML=[['Findings',rows.length,'Read-only audit observations'],['High risk',high,'Priority investigation'],['Medium risk',medium,'Follow-up required'],['Scope',scope==='ALL'?'Full system':scope,'Current audit lens']].map(x=>`<article><small>${esc(x[0])}</small><b>${esc(x[1])}</b><span>${esc(x[2])}</span></article>`).join('');const body=$('advancedAuditFindingsBody');if(body)body.innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.Scope)}</td><td><b>${esc(r.Control)}</b></td><td>${esc(r.Record)}</td><td class="wrap">${esc(r.Finding)}</td><td><span class="audit-risk-pill ${String(r.Risk).toLowerCase()}">${esc(r.Risk)}</span></td><td class="wrap">${esc(r['Required action'])}</td></tr>`).join(''):'<tr class="empty-row"><td colspan="6"><div class="table-empty"><b>No exceptions detected in this scope</b><span>This is a deterministic read-only screening result; the Internal Auditor retains professional judgment.</span></div></td></tr>';}
  async function runAdvancedAuditorAudit(){if(!advancedAuditorAllowed())return toast('Advanced audit tools are restricted to Internal Auditor authority.');await loadMtsData();if(canUseRecoveryAssurance())await loadRecoveryAssurance(true);renderAdvancedAuditorTools();toast('Advanced read-only audit tests completed.');}
  async function exportAdvancedAuditorFindings(){if(!advancedAuditorAllowed())return toast('Advanced audit tools are restricted to Internal Auditor authority.');const rows=advancedAuditorFindings($('advancedAuditScope')?.value||'ALL');if(!rows.length)return toast('There are no audit findings to export in this scope.');try{await createGovernedReport('audit','all',$('advancedAuditFormat')?.value||'excel',rows);}catch(err){toast(err.message||'Could not export audit findings.');}}
  function bindReportingAuditRetentionUi(){if(document.body.dataset.reportingAuditBound==='true')return;document.body.dataset.reportingAuditBound='true';$('systemReportType')?.addEventListener('change',()=>renderReportGenerator());$('systemReportPeriod')?.addEventListener('change',()=>renderReportGenerator());$('systemReportGenerate')?.addEventListener('click',generateSelectedSystemReport);$('advancedAuditScope')?.addEventListener('change',renderAdvancedAuditorTools);$('runAdvancedAuditorAudit')?.addEventListener('click',runAdvancedAuditorAudit);$('exportAdvancedAuditorFindings')?.addEventListener('click',exportAdvancedAuditorFindings);}
