// Assurance Regent v6.3.78 — Google Meet transcript -> Jivan interview evidence
// Private Meet data requires OAuth. The optional API key is used only for Google project/quota identification.
declare const Deno:any;

const cors={
  'Access-Control-Allow-Origin':'*',
  'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods':'POST, OPTIONS'
};
const MEET_SCOPE='https://www.googleapis.com/auth/meetings.space.readonly';
function json(body:any,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});}
function env(name:string){return String(Deno.env.get(name)||'').trim();}
function baseUrl(){const v=env('SUPABASE_URL');if(!v)throw new Error('SUPABASE_URL is unavailable.');return v.replace(/\/$/,'');}
function serviceKey(){const v=env('SUPABASE_SERVICE_ROLE_KEY');if(!v)throw new Error('SUPABASE_SERVICE_ROLE_KEY is required.');return v;}
function publishableKey(){const raw=env('SUPABASE_PUBLISHABLE_KEYS');if(raw){try{const x=JSON.parse(raw);if(x?.default)return String(x.default);const first=Object.values(x||{})[0];if(first)return String(first);}catch{}}return env('SUPABASE_PUBLISHABLE_KEY')||env('SUPABASE_ANON_KEY');}
function clean(v:any,max=12000){return String(v??'').trim().replace(/[\u0000-\u001f]/g,' ').slice(0,max);}
async function sf(path:string,init:any={}){const k=serviceKey(),r=await fetch(`${baseUrl()}${path}`,{...init,headers:{apikey:k,Authorization:`Bearer ${k}`,...(init.headers||{})}});const t=await r.text();let b:any=null;try{b=t?JSON.parse(t):null;}catch{b=t;}if(!r.ok)throw new Error(b?.message||b?.error||b?.hint||String(b||`Supabase service request failed (${r.status}).`));return b;}
async function browserRpc(name:string,payload:any={}){const k=publishableKey();if(!k)throw new Error('Supabase publishable key is unavailable.');const r=await fetch(`${baseUrl()}/rest/v1/rpc/${encodeURIComponent(name)}`,{method:'POST',headers:{apikey:k,'Content-Type':'application/json'},body:JSON.stringify(payload)});const t=await r.text();let b:any=null;try{b=t?JSON.parse(t):null;}catch{b=t;}if(!r.ok)throw new Error(b?.message||b?.error||b?.hint||String(b||`RPC ${name} failed (${r.status}).`));return b;}
async function serviceRpc(name:string,payload:any={}){return sf(`/rest/v1/rpc/${encodeURIComponent(name)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});}
async function verifyHr(token:string){if(!token)throw new Error('Sign in before using Jivan interview notes.');const ctx=await browserRpc('assurance_regent_browser_agent_context',{p_token:token}),authority=String(ctx?.authority||'').toUpperCase();if(!['DEVELOPER','CEO','ADMINISTRATOR','HR_MANAGER'].includes(authority))throw new Error('Human Resources recruitment authority is required.');if(!ctx?.actor?.id)throw new Error('Signed-in user could not be verified.');return ctx;}
async function oauthCredentials(){const x=await serviceRpc('assurance_regent_gmail_oauth_credentials',{});const clientId=clean(x?.client_id,500),clientSecret=clean(x?.client_secret,500);if(!clientId||!clientSecret)throw new Error('Google OAuth credentials are not configured.');return {clientId,clientSecret};}
async function meetApiKey(){try{return clean(await serviceRpc('assurance_regent_google_meet_api_key',{}),500);}catch{return '';}}
async function connection(actorId:string){const rows=await sf(`/rest/v1/assurance_regent_gmail_connections?actor_id=eq.${encodeURIComponent(actorId)}&select=actor_id,gmail_email,refresh_token,granted_scope,revoked_at&limit=1`,{headers:{Accept:'application/json'}});return rows?.[0]||null;}
async function refreshAccess(refreshToken:string){const {clientId,clientSecret}=await oauthCredentials(),form=new URLSearchParams();form.set('client_id',clientId);form.set('client_secret',clientSecret);form.set('refresh_token',refreshToken);form.set('grant_type','refresh_token');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form.toString()});const t=await r.text();let b:any={};try{b=t?JSON.parse(t):{};}catch{b={error_description:t};}if(!r.ok)throw new Error(b?.error_description||b?.error||`Google token refresh failed (${r.status}).`);return b;}
function meetCode(url:any){try{const u=new URL(String(url||''));if(u.hostname!=='meet.google.com')return '';return clean(u.pathname.split('/').filter(Boolean)[0],160).toLowerCase();}catch{return '';}}
function participantLabel(p:any){return clean(p?.signedinUser?.displayName||p?.anonymousUser?.displayName||p?.phoneUser?.displayName||'Participant',200);}
async function googleGet(path:string,access:string,apiKey=''){const u=new URL(`https://meet.googleapis.com/v2/${path.replace(/^\//,'')}`);if(apiKey)u.searchParams.set('key',apiKey);const r=await fetch(u,{headers:{Authorization:`Bearer ${access}`}});const t=await r.text();let b:any=null;try{b=t?JSON.parse(t):null;}catch{b=t;}if(!r.ok)throw new Error(b?.error?.message||b?.message||`Google Meet API failed (${r.status}).`);return b;}
async function listConferenceRecords(code:string,access:string,key:string){const filter=`space.meeting_code = "${code.replace(/"/g,'')}"`,u=`conferenceRecords?filter=${encodeURIComponent(filter)}&pageSize=50`;const b=await googleGet(u,access,key);return Array.isArray(b?.conferenceRecords)?b.conferenceRecords:[];}
function nearestConference(rows:any[],scheduled:any){const target=new Date(String(scheduled||'')).getTime();return [...rows].sort((a,b)=>Math.abs(new Date(a.startTime||0).getTime()-target)-Math.abs(new Date(b.startTime||0).getTime()-target))[0]||null;}
async function listParticipants(parent:string,access:string,key:string){let token='',out:any[]=[];for(let i=0;i<5;i++){const q=`${parent}/participants?pageSize=250${token?`&pageToken=${encodeURIComponent(token)}`:''}`,b=await googleGet(q,access,key);out.push(...(b?.participants||[]));token=String(b?.nextPageToken||'');if(!token)break;}return out;}
async function listTranscriptEntries(parent:string,access:string,key:string){const ts=await googleGet(`${parent}/transcripts?pageSize=100`,access,key),transcripts=Array.isArray(ts?.transcripts)?ts.transcripts:[];if(!transcripts.length)return {transcript:null,entries:[]};const transcript=transcripts[transcripts.length-1];let token='',entries:any[]=[];for(let i=0;i<40;i++){const q=`${transcript.name}/entries?pageSize=100${token?`&pageToken=${encodeURIComponent(token)}`:''}`,b=await googleGet(q,access,key);entries.push(...(b?.transcriptEntries||[]));token=String(b?.nextPageToken||'');if(!token)break;}return {transcript,entries};}
async function sha256(text:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function outputText(data:any){if(typeof data?.output_text==='string')return data.output_text;for(const item of data?.output||[])for(const c of item?.content||[])if(typeof c?.text==='string')return c.text;return '';}
function parseJson(text:string){const s=String(text||'').replace(/```(?:json)?/gi,'').replace(/```/g,'').trim();try{return JSON.parse(s);}catch{}const a=s.indexOf('{'),z=s.lastIndexOf('}');if(a>=0&&z>a)return JSON.parse(s.slice(a,z+1));throw new Error('Jivan returned an unreadable interview note set.');}
async function analyzeWithJivan(candidate:any,vacancy:any,transcriptText:string,participants:any[]){const key=env('OPENAI_API_KEY');if(!key)throw new Error('OPENAI_API_KEY is not configured for Jivan interview notes.');const model=env('OPENAI_MODEL')||'gpt-5-mini';const criteria={title:clean(vacancy?.title||candidate?.vacancy_title,200),department:clean(vacancy?.department,160),requirements:clean(vacancy?.publicRequirements,7000),responsibilities:clean(vacancy?.publicResponsibilities,7000),skills:clean(vacancy?.publicSkills,5000),education:clean(vacancy?.publicEducation,2500)};const prompt=`You are Jivan's interview-note specialist in Assurance Regent. Produce ADVISORY interview evidence for HR from an authorized Google Meet transcript. Do NOT make, recommend, rank, or automate a hiring decision. Evaluate only explicit job-related evidence in the transcript and the vacancy criteria. Do not infer age, sex, gender, race, ethnicity, religion, disability, health, family status, nationality, political views, personality disorders, emotions, or other sensitive traits. Missing evidence must be marked missing rather than invented. Return ONLY JSON with this schema: {"candidate":"","summary":"","question_notes":[{"question":"","response_summary":"","evidence":""}],"criteria":[{"criterion":"","evidence":"","status":"DEMONSTRATED|PARTIAL|NOT_EVIDENCED"}],"strengths":[],"gaps":[],"follow_up_questions":[],"panel_notes":"","human_decision_required":true}.\nCANDIDATE: ${clean(candidate?.applicant_name||candidate?.candidate_name,200)}\nVACANCY: ${JSON.stringify(criteria)}\nPARTICIPANTS: ${JSON.stringify(participants.map((p:any)=>participantLabel(p)).slice(0,80))}\nTRANSCRIPT:\n${transcriptText.slice(0,120000)}`;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,input:prompt,store:false,max_output_tokens:4200})});const t=await r.text();let b:any=null;try{b=t?JSON.parse(t):null;}catch{b={error:{message:t}};}if(!r.ok)throw new Error(b?.error?.message||`Jivan interview analysis failed (${r.status}).`);const x=parseJson(outputText(b));x.human_decision_required=true;delete x.score;delete x.rank;delete x.recommendation;delete x.selected;return x;}
async function savedNote(interviewId:string){const rows=await sf(`/rest/v1/assurance_regent_recruitment_interview_notes?interview_id=eq.${encodeURIComponent(interviewId)}&select=*&limit=1`,{headers:{Accept:'application/json'}});return rows?.[0]||null;}
async function saveNote(row:any){const rows=await sf('/rest/v1/assurance_regent_recruitment_interview_notes?on_conflict=interview_id',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(row)});return rows?.[0]||row;}

Deno.serve(async(req:any)=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
  if(req.method!=='POST')return json({error:'POST is required.'},405);
  try{
    const body=await req.json().catch(()=>({})),action=clean(body?.action,60).toLowerCase(),token=clean(body?.session_token,5000),ctx=await verifyHr(token),actor=ctx.actor,auth=String(ctx.authority||'').toUpperCase();
    const c=await connection(String(actor.id)),hasScope=Boolean(c&&!c.revoked_at&&c.refresh_token&&String(c.granted_scope||'').split(/\s+/).includes(MEET_SCOPE));
    if(action==='status')return json({ok:true,connected:Boolean(c&&!c.revoked_at&&c.refresh_token),meet_scope:hasScope,email:c?.gmail_email||'',scope:MEET_SCOPE});
    if(!hasScope)return json({error:'Connect Google Workspace again and approve Google Meet read access before Jivan can read interview transcripts.',code:'MEET_SCOPE_REQUIRED',needs_auth:true},409);
    const bundle=await browserRpc('assurance_regent_browser_recruitment_bundle',{p_token:token}),interviewId=clean(body?.interview_id,160),interview=(bundle?.interviews||[]).find((x:any)=>String(x.id||'')===interviewId);if(!interview)throw new Error('Interview not found or not permitted.');if(auth!=='DEVELOPER'&&String(interview.company_id||'')!==String(actor.companyId||''))throw new Error('This interview belongs to another company.');
    if(action==='get'){const note=await savedNote(interviewId);return json({ok:true,note});}
    if(action==='analyze'){
      const code=meetCode(interview.meet_url);if(!code)throw new Error('This interview does not have a valid Google Meet room.');let access;try{access=await refreshAccess(c.refresh_token);}catch{return json({error:'Google authorization expired. Reconnect Google Workspace.',code:'GOOGLE_RECONNECT_REQUIRED',needs_auth:true},409);}const accessToken=clean(access?.access_token,5000),apiKey=await meetApiKey();
      const records=await listConferenceRecords(code,accessToken,apiKey),record=nearestConference(records,interview.scheduled_at);if(!record)return json({error:'No Google Meet conference record was found for this interview yet.',code:'CONFERENCE_NOT_FOUND'},404);
      const participants=await listParticipants(record.name,accessToken,apiKey),artifact=await listTranscriptEntries(record.name,accessToken,apiKey);if(!artifact.transcript||!artifact.entries.length)return json({error:'The interview transcript is not available yet. Google Meet transcription must be enabled during the interview; then try again after the call ends.',code:'TRANSCRIPT_NOT_READY'},409);
      const labels=new Map(participants.map((p:any)=>[String(p.name||''),participantLabel(p)])),lines=artifact.entries.map((e:any)=>`${labels.get(String(e.participant||''))||'Participant'}: ${clean(e.text,12000)}`),transcriptText=lines.join('\n'),hash=await sha256(transcriptText),existing=await savedNote(interviewId);if(existing?.transcript_hash===hash&&!body?.force)return json({ok:true,note:existing,cached:true});
      const app=(bundle?.applications||[]).find((x:any)=>String(x.id||'')===String(interview.application_id||''))||interview,vacancy=(ctx?.state?.live?.vacancies||[]).find((x:any)=>String(x.id||'')===String(interview.vacancy_id||app.vacancy_id||''))||{};
      const analysis=await analyzeWithJivan(app,vacancy,transcriptText,participants),saved=await saveNote({interview_id:interviewId,company_id:String(interview.company_id||app.company_id||''),application_id:String(interview.application_id||app.id||''),vacancy_id:String(interview.vacancy_id||app.vacancy_id||''),candidate_name:String(interview.candidate_name||app.applicant_name||''),conference_record:String(record.name||''),transcript_name:String(artifact.transcript.name||''),transcript_hash:hash,participant_count:participants.length,analysis,generated_by:String(actor.id),generated_at:existing?.generated_at||new Date().toISOString(),updated_at:new Date().toISOString()});return json({ok:true,note:saved,cached:false});
    }
    if(action==='compare'){
      const vacancyId=clean(body?.vacancy_id,160);if(!vacancyId)throw new Error('Select one vacancy before comparing interview evidence.');const rows=await sf(`/rest/v1/assurance_regent_recruitment_interview_notes?company_id=eq.${encodeURIComponent(auth==='DEVELOPER'?String(body?.company_id||actor.companyId||''):String(actor.companyId||''))}&vacancy_id=eq.${encodeURIComponent(vacancyId)}&select=interview_id,candidate_name,analysis,updated_at&order=updated_at.asc`,{headers:{Accept:'application/json'}});return json({ok:true,vacancy_id:vacancyId,candidates:rows||[],human_decision_required:true,ranking_provided:false});
    }
    return json({error:'Unknown Meet interview assistant action.'},400);
  }catch(err:any){const m=String(err?.message||err||'Meet interview assistant failed.');const status=/sign in|session|verified/i.test(m)?401:/authority|another company|not permitted/i.test(m)?403:400;return json({error:m},status);}
});
