declare const Deno:any;
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,x-client-info,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS'};
const env=(n:string)=>String(Deno.env.get(n)||'').trim();
const clean=(v:any,n=300)=>String(v??'').trim().replace(/[\u0000-\u001f]/g,' ').slice(0,n);
const q=(v:any)=>encodeURIComponent(String(v??''));
const base=()=>env('SUPABASE_URL').replace(/\/$/,'');const service=()=>env('SUPABASE_SERVICE_ROLE_KEY');
async function sf(path:string,init:any={}){const r=await fetch(base()+path,{...init,headers:{apikey:service(),Authorization:`Bearer ${service()}`,...(init.headers||{})}});const t=await r.text();let b:any=null;try{b=t?JSON.parse(t):null}catch{b=t}if(!r.ok)throw new Error(b?.message||b?.error||String(b||`HTTP ${r.status}`));return b;}
const rpc=(name:string,payload:any)=>sf(`/rest/v1/rpc/${q(name)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload||{})});
async function removePaths(paths:string[]){for(let i=0;i<paths.length;i+=100){const batch=paths.slice(i,i+100);if(!batch.length)continue;await sf('/storage/v1/object/assurance-regent-files',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({prefixes:batch})});}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return new Response(JSON.stringify({error:'POST required'}),{status:405,headers:{...CORS,'content-type':'application/json'}});try{const z:any=await req.json().catch(()=>({})),token=clean(z.session_token,260),companyId=clean(z.company_id,180),confirmation=clean(z.confirmation,220),mode=clean(z.mode,30).toLowerCase()||'preview';if(!token||!companyId)throw new Error('Developer session and company ID are required.');const preview=await rpc('assurance_regent_browser_admin_company_purge_preview',{p_token:token,p_company_id:companyId});if(mode==='preview')return new Response(JSON.stringify(preview),{headers:{...CORS,'content-type':'application/json','cache-control':'no-store'}});if(mode!=='purge')throw new Error('Unknown company purge action.');if(confirmation!==String(preview?.confirmation||''))throw new Error(`Type ${preview?.confirmation||'the confirmation phrase'} exactly to permanently delete this company.`);const files=await sf(`/rest/v1/assurance_regent_files?company_id=eq.${q(companyId)}&deleted_at=is.null&select=id,storage_path,status`);const paths=(Array.isArray(files)?files:[]).map((x:any)=>String(x.storage_path||'')).filter(Boolean);await removePaths(paths);const result=await rpc('assurance_regent_browser_admin_company_purge_commit',{p_token:token,p_company_id:companyId,p_confirmation:confirmation});return new Response(JSON.stringify({...result,storageObjectsDeleted:paths.length}),{headers:{...CORS,'content-type':'application/json','cache-control':'no-store'}});}catch(e:any){return new Response(JSON.stringify({error:String(e?.message||e)}),{status:400,headers:{...CORS,'content-type':'application/json','cache-control':'no-store'}});}});